#!/bin/bash

# Initialization
STARTED=0
TRAPS_SET=0
[ -z "$DASH_ROOT" ] && DASH_ROOT="$( cd "$( dirname "$0" )" && pwd )"
[ -z "$DASH_INI_PATH" ] && DASH_INI_PATH="~/.dash.ini"
if [ -f "$DASH_INI_PATH" ]; then
	function load_config(){
		RET="$(awk -F "\\\\s*=\\\\s*" "/^$1=/"' {print $2}'\
			"$DASH_INI_PATH")"
		[ -n "$RET" ] && echo $RET || echo $2
	}
else
	function load_config(){ echo $2; }
fi

# Dash basic configuration
DBG=$(load_config "DBG" '0')
REFRESH_RATE_SECONDS=$(load_config "REFRESH_RATE_SECONDS" '120')
SECTION_MIN_COLS=$(load_config "SECTION_MIN_COLS" '40')
SECTION_MIN_ROWS=$(load_config "SECTION_MIN_ROWS" '3')

# Display configuration
DISPLAY_ENCODING=$(load_config "DISPLAY_ENCODING" 'ASCII')
DISPLAY_COLOR_PALETTE=$(load_config "DISPLAY_COLOR_PALETTE" '16')
DISPLAY_ESCAPE_SPACE='`'
if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
	DISPLAY_SEPARATOR_V=$(load_config "DISPLAY_SEPARATOR_V" '│')
	DISPLAY_SEPARATOR_H=$(load_config "DISPLAY_SEPARATOR_H" '─')
	DISPLAY_SEPARATOR_C=$(load_config "DISPLAY_SEPARATOR_C" '┼')
	DISPLAY_SEPARATOR_T=$(load_config "DISPLAY_SEPARATOR_T" '┬')
	DISPLAY_SEPARATOR_B=$(load_config "DISPLAY_SEPARATOR_B" '┴')
	DISPLAY_SEPARATOR_L=$(load_config "DISPLAY_SEPARATOR_L" '├')
	DISPLAY_SEPARATOR_R=$(load_config "DISPLAY_SEPARATOR_R" '┤')
	DISPLAY_SEPARATOR_TL=$(load_config "DISPLAY_SEPARATOR_TL" '┌')
	DISPLAY_SEPARATOR_TR=$(load_config "DISPLAY_SEPARATOR_TR" '┐')
	DISPLAY_SEPARATOR_BL=$(load_config "DISPLAY_SEPARATOR_BL" '└')
	DISPLAY_SEPARATOR_BR=$(load_config "DISPLAY_SEPARATOR_BR" '┘')
else
	DISPLAY_SEPARATOR_V=$(load_config "DISPLAY_SEPARATOR_V" '|')
	DISPLAY_SEPARATOR_H=$(load_config "DISPLAY_SEPARATOR_H" '-')
	DISPLAY_SEPARATOR_C=$(load_config "DISPLAY_SEPARATOR_C" '+')
	DISPLAY_SEPARATOR_T=$(load_config "DISPLAY_SEPARATOR_T" '-')
	DISPLAY_SEPARATOR_B=$(load_config "DISPLAY_SEPARATOR_B" '-')
	DISPLAY_SEPARATOR_L=$(load_config "DISPLAY_SEPARATOR_L" '|')
	DISPLAY_SEPARATOR_R=$(load_config "DISPLAY_SEPARATOR_R" '|')
	DISPLAY_SEPARATOR_TL=$(load_config "DISPLAY_SEPARATOR_TL" '+')
	DISPLAY_SEPARATOR_TR=$(load_config "DISPLAY_SEPARATOR_TR" '+')
	DISPLAY_SEPARATOR_BL=$(load_config "DISPLAY_SEPARATOR_BL" '+')
	DISPLAY_SEPARATOR_BR=$(load_config "DISPLAY_SEPARATOR_BR" '+')
fi

# Color palette configuration
if [ "$DISPLAY_COLOR_PALETTE" == "256" ]; then
	COLOR_RESET="[0;39;49m"
	COLOR_BOLD="[1m"
	COLOR_ULINE="[4m"
	COLOR_BOLD_OFF="[0m"
	COLOR_ULINE_OFF="[0m"
	COLOR_NORM="[0;39m"
	COLOR_GREN="[38;5;118m"
	COLOR_BLUE="[38;5;26m"
	COLOR_LBLU="[38;5;81m"
	COLOR_RED="[38;5;160m"
	COLOR_RED2="[38;5;161m"
	COLOR_PURP="[38;5;135m"
	COLOR_ORNG="[38;5;208m"
	COLOR_YELO="[38;5;227m"
	COLOR_GRAY="[38;5;245m"
	COLOR_LGRY="[38;5;249m"
	COLOR_DGRY="[38;5;236m"
	COLOR_WHIT="[38;5;15m"
	COLOR_BLCK="[38;5;0m"
	COLOR_BG_NORM="[49m"
	COLOR_BG_GREN="[48;5;118m"
	COLOR_BG_BLUE="[48;5;26m"
	COLOR_BG_LBLU="[48;5;81m"
	COLOR_BG_RED="[48;5;160m"
	COLOR_BG_RED2="[48;5;161m"
	COLOR_BG_PURP="[48;5;135m"
	COLOR_BG_ORNG="[48;5;208m"
	COLOR_BG_YELO="[48;5;227m"
	COLOR_BG_GRAY="[48;5;245m"
	COLOR_BG_LGRY="[48;5;249m"
	COLOR_BG_DGRY="[48;5;236m"
	COLOR_BG_WHIT="[48;5;15m"
	COLOR_BG_BLCK="[48;5;0m"
	COLOR_HEAT_0="[38;5;21m"
	COLOR_HEAT_1="[38;5;63m"
	COLOR_HEAT_2="[38;5;147m"
	COLOR_HEAT_3="[38;5;231m"
	COLOR_HEAT_4="[38;5;217m"
	COLOR_HEAT_5="[38;5;203m"
	COLOR_HEAT_6="[38;5;196m"
	COLOR_BG_HEAT_0="[48;5;21m"
	COLOR_BG_HEAT_1="[48;5;63m"
	COLOR_BG_HEAT_2="[48;5;147m"
	COLOR_BG_HEAT_3="[48;5;231m"
	COLOR_BG_HEAT_4="[48;5;217m"
	COLOR_BG_HEAT_5="[48;5;203m"
	COLOR_BG_HEAT_6="[48;5;196m"
elif [ "$DISPLAY_COLOR_PALETTE" == "16" ]; then
	COLOR_RESET="[0;39;49m"
	COLOR_BOLD="[1m"
	COLOR_ULINE="[4m"
	COLOR_BOLD_OFF="[0m"
	COLOR_ULINE_OFF="[0m"
	COLOR_NORM="[0;39m"
	COLOR_GREN="[32m"
	COLOR_BLUE="[1;34m"
	COLOR_LBLU="[1;36m"
	COLOR_RED="[31m"
	COLOR_RED2="[31m"
	COLOR_PURP="[35m"
	COLOR_ORNG="[33m"
	COLOR_YELO="[1;33m"
	COLOR_GRAY="[37m"
	COLOR_LGRY="[37m"
	COLOR_DGRY="[1;30m"
	COLOR_WHIT="[1;37m"
	COLOR_BLCK="[30m"
	COLOR_BG_NORM="[0;49m"
	COLOR_BG_GREN="[42m"
	COLOR_BG_BLUE="[1;44m"
	COLOR_BG_LBLU="[1;46m"
	COLOR_BG_RED="[41m"
	COLOR_BG_RED2="[41m"
	COLOR_BG_PURP="[45m"
	COLOR_BG_ORNG="[43m"
	COLOR_BG_YELO="[1;43m"
	COLOR_BG_GRAY="[47m"
	COLOR_BG_LGRY="[47m"
	COLOR_BG_DGRY="[1;40m"
	COLOR_BG_WHIT="[1;47m"
	COLOR_BG_BLCK="[40m"
	COLOR_HEAT_0="[34m"
	COLOR_HEAT_1="[1;34m"
	COLOR_HEAT_2="[36m"
	COLOR_HEAT_3="[1;36m"
	COLOR_HEAT_4="[37m"
	COLOR_HEAT_5="[1;31m"
	COLOR_HEAT_6="[31m"
	COLOR_BG_HEAT_0="[44m"
	COLOR_BG_HEAT_1="[1;44m"
	COLOR_BG_HEAT_2="[46m"
	COLOR_BG_HEAT_3="[1;46m"
	COLOR_BG_HEAT_4="[47m"
	COLOR_BG_HEAT_5="[1;41m"
	COLOR_BG_HEAT_6="[41m"
elif [ "$DISPLAY_COLOR_PALETTE" == "8" ]; then
	COLOR_RESET="[0;39;49m"
	COLOR_BOLD=""
	COLOR_ULINE=""
	COLOR_BOLD_OFF=""
	COLOR_ULINE_OFF=""
	COLOR_NORM="[39m"
	COLOR_GREN="[32m"
	COLOR_BLUE="[34m"
	COLOR_LBLU="[34m"
	COLOR_RED="[31m"
	COLOR_RED2="[31m"
	COLOR_PURP="[35m"
	COLOR_ORNG="[33m"
	COLOR_YELO="[33m"
	COLOR_GRAY="[37m"
	COLOR_LGRY="[37m"
	COLOR_DGRY="[37m"
	COLOR_WHIT="[37m"
	COLOR_BLCK="[30m"
	COLOR_BG_NORM="[49m"
	COLOR_BG_GREN="[42m"
	COLOR_BG_BLUE="[44m"
	COLOR_BG_LBLU="[44m"
	COLOR_BG_RED="[41m"
	COLOR_BG_RED2="[41m"
	COLOR_BG_PURP="[45m"
	COLOR_BG_ORNG="[43m"
	COLOR_BG_YELO="[43m"
	COLOR_BG_GRAY="[47m"
	COLOR_BG_LGRY="[47m"
	COLOR_BG_DGRY="[47m"
	COLOR_BG_WHIT="[47m"
	COLOR_BG_BLCK="[40m"
	COLOR_HEAT_0="[34m"
	COLOR_HEAT_1="[34m"
	COLOR_HEAT_2="[36m"
	COLOR_HEAT_3="[36m"
	COLOR_HEAT_4="[37m"
	COLOR_HEAT_5="[31m"
	COLOR_HEAT_6="[31m"
	COLOR_BG_HEAT_0="[44m"
	COLOR_BG_HEAT_1="[44m"
	COLOR_BG_HEAT_2="[46m"
	COLOR_BG_HEAT_3="[46m"
	COLOR_BG_HEAT_4="[47m"
	COLOR_BG_HEAT_5="[41m"
	COLOR_BG_HEAT_6="[41m"
fi

# Control functions
function msg(){
	echo -e "$COLOR_RESET$COLOR_GRAY[Dash]$COLOR_NORM $1\n"
}
function error(){
	echo -e "$COLOR_RESET$COLOR_GRAY[Dash] $COLOR_RED""Error:$COLOR_NORM $1\n"\
		>&2
	if [ "$TRAPS_SET" -eq "1" ]; then
		read -p "$(echo -e '[Press ENTER to exit]\n\b')" TMP
	fi
	if [[ -z "$2" ]]; then exit 1; fi; exit "$2"
}
function handleWindowChange(){
	render_sections
}
function handleInterrupt(){
	exit 0
}
function handleExit(){
	stty echo
	tput rmcup
}

# Output formatting functions
function center(){
	LEN=$(echo -en "$1" | sed "s/[^m]*m//g" | wc -m)
	if [ "$LEN" -lt "$2" ]; then
		printf "%*s%s\n" $(( ($2 - $LEN + 1) / 2)) " " "$1"
	else
		echo "$1"
	fi
}
function truncate(){
	LEN=$(echo -en "$1" | sed "s/[^m]*m//g" | wc -m)
	if [ "$LEN" -gt "$2" ];then
		echo -n "${1:0:$(( $2 - 3))}..."
	else
		echo -n "$1"
	fi
}
function extend(){
	LEN=$(echo -en "$1" | sed "s/[^m]*m//g" | wc -m)
	if [ "$LEN" -lt "$2" ];then
		printf "%s%*s" "$1" $(($2 - $LEN)) " "
	else
		echo -n "$1"
	fi
}
function extendl(){
	LEN=$(echo -en "$1" | sed "s/[^m]*m//g" | wc -m)
	if [ "$LEN" -lt "$2" ];then
		printf "%*s%s" $(($2 - $LEN)) " " "$1"
	else
		echo -n "$1"
	fi
}
function centerex(){
	echo "$(extend "$(center "$1" $2)" $2)"
}
function randomize(){
	LEN=$(( (${#1}>10?9:${#1}) - 1 ))
	RET=""
	ORDER=""
	while [ "${#ORDER}" -lt "$2" ]; do
		ORDER=$ORDER$(grep -o "[0-$LEN]"<<<$(date +%s%3N|md5sum)|paste -sd "")
	done
	for i in `seq 0 $(($2 - 1))`; do
		POS=${ORDER:$i:1}
		RET="$RET"${1:$POS:1}
	done
	echo $RET
}
function heat(){
	COLORS=("$COLOR_HEAT_0" "$COLOR_HEAT_1" "$COLOR_HEAT_2" "$COLOR_HEAT_3"\
		"$COLOR_HEAT_4" "$COLOR_HEAT_5" "$COLOR_HEAT_6")
	BGCOLORS=("$COLOR_BG_HEAT_0" "$COLOR_BG_HEAT_1" "$COLOR_BG_HEAT_2"\
		"$COLOR_BG_HEAT_3" "$COLOR_BG_HEAT_4" "$COLOR_BG_HEAT_5"\
		"$COLOR_BG_HEAT_6")
	RANGE="$(echo "$3 - $2" | bc -l)"
	VALUE="$(echo "$1 - $2" | tr -d "%[:alpha:]" | bc -l)"
	SCALE="$(echo "$VALUE * 7 / $RANGE" | bc -l)"
	INDEX=${SCALE%.*}
	if [ -z "$4" ]; then
		echo -en "${COLORS[$(( INDEX>6 ? 6 : INDEX ))]}$1$COLOR_RESET"
	else
		echo -en "${BGCOLORS[$(( INDEX>6 ? 6 : INDEX ))]}$1$COLOR_RESET"
	fi
}
function fmt_mem(){
	MEM=$1
	UNITS=("B KiB MiB GiB TiB PiB EiB ZiB YiB")
	for UNIT in $UNITS; do
		if [ "${MEM%.*}" -lt "1024" ]; then
			echo "$MEM$UNIT"
			return
		else
			MEM="$(echo "scale=$2; $MEM / 1024.00" | bc)"
		fi
	done
	echo $MEM"YiB"
}
function percent_bar(){
	USE_WIDTH=$(printf "%.0f" "$(echo "$1*$2" | bc)")
	USE_PERC=$(printf "%2.0f" "$(echo "$1*100" | bc)")
	RET=$4$COLOR_DGRY
	for POS in `seq 0 $(( $2-1 ))`; do
		if [ "$POS" -eq "$USE_WIDTH" ]; then
			RET=$RET$COLOR_BG_DGRY$3
		fi
		if [ "$POS" -eq "$(( ($2+1)/2 - 1 ))" ]; then
			RET=$RET${USE_PERC:0:1}
		elif [ "$POS" -eq "$(( ($2+1)/2 ))" ]; then
			RET=$RET${USE_PERC:1:1}
		elif [ "$POS" -eq "$(( ($2+1)/2 + 1 ))" ]; then
			RET=$RET"%"
		else
			RET=$RET" "
		fi
	done
	echo -n "$RET$COLOR_RESET"
}
declare -A LARGE_READ_OUT
LARGE_READ_OUT["0",0]=" XXX "
LARGE_READ_OUT["0",1]="X   X"
LARGE_READ_OUT["0",2]="X   X"
LARGE_READ_OUT["0",3]="X   X"
LARGE_READ_OUT["0",4]=" XXX "
LARGE_READ_OUT["1",0]="  X  "
LARGE_READ_OUT["1",1]=" XX  "
LARGE_READ_OUT["1",2]="  X  "
LARGE_READ_OUT["1",3]="  X  "
LARGE_READ_OUT["1",4]=" XXX "
LARGE_READ_OUT["2",0]=" XXX "
LARGE_READ_OUT["2",1]="X   X"
LARGE_READ_OUT["2",2]="  XX "
LARGE_READ_OUT["2",3]=" X   "
LARGE_READ_OUT["2",4]="XXXXX"
LARGE_READ_OUT["3",0]="XXXX "
LARGE_READ_OUT["3",1]="    X"
LARGE_READ_OUT["3",2]=" XXX "
LARGE_READ_OUT["3",3]="    X"
LARGE_READ_OUT["3",4]="XXXX "
LARGE_READ_OUT["4",0]="   X "
LARGE_READ_OUT["4",1]="  XX "
LARGE_READ_OUT["4",2]=" X X "
LARGE_READ_OUT["4",3]="XXXXX"
LARGE_READ_OUT["4",4]="   X "
LARGE_READ_OUT["5",0]="XXXXX"
LARGE_READ_OUT["5",1]="X    "
LARGE_READ_OUT["5",2]="XXXX "
LARGE_READ_OUT["5",3]="    X"
LARGE_READ_OUT["5",4]="XXXX "
LARGE_READ_OUT["6",0]=" XXXX"
LARGE_READ_OUT["6",1]="X    "
LARGE_READ_OUT["6",2]="XXXX "
LARGE_READ_OUT["6",3]="X   X"
LARGE_READ_OUT["6",4]=" XXX "
LARGE_READ_OUT["7",0]="XXXXX"
LARGE_READ_OUT["7",1]="    X"
LARGE_READ_OUT["7",2]="   X "
LARGE_READ_OUT["7",3]="  X  "
LARGE_READ_OUT["7",4]="  X  "
LARGE_READ_OUT["8",0]=" XXX "
LARGE_READ_OUT["8",1]="X   X"
LARGE_READ_OUT["8",2]=" XXX "
LARGE_READ_OUT["8",3]="X   X"
LARGE_READ_OUT["8",4]=" XXX "
LARGE_READ_OUT["9",0]=" XXX "
LARGE_READ_OUT["9",1]="X   X"
LARGE_READ_OUT["9",2]="XXXXX"
LARGE_READ_OUT["9",3]="    X"
LARGE_READ_OUT["9",4]="XXXX "
LARGE_READ_OUT["-",0]="     "
LARGE_READ_OUT["-",1]="     "
LARGE_READ_OUT["-",2]=" XXXX"
LARGE_READ_OUT["-",3]="     "
LARGE_READ_OUT["-",4]="     "
LARGE_READ_OUT["F",0]="XXXXX"
LARGE_READ_OUT["F",1]="X    "
LARGE_READ_OUT["F",2]="XXXX "
LARGE_READ_OUT["F",3]="X    "
LARGE_READ_OUT["F",4]="X    "
LARGE_READ_OUT["C",0]=" XXX "
LARGE_READ_OUT["C",1]="X   X"
LARGE_READ_OUT["C",2]="X    "
LARGE_READ_OUT["C",3]="X   X"
LARGE_READ_OUT["C",4]=" XXX "
LARGE_READ_OUT[".",0]="     "
LARGE_READ_OUT[".",1]="     "
LARGE_READ_OUT[".",2]="     "
LARGE_READ_OUT[".",3]="     "
LARGE_READ_OUT[".",4]="  X  "
LARGE_READ_OUT["°",0]=" XXX "
LARGE_READ_OUT["°",1]=" X X "
LARGE_READ_OUT["°",2]=" XXX "
LARGE_READ_OUT["°",3]="     "
LARGE_READ_OUT["°",4]="     "
LARGE_READ_OUT["'",0]=" XXX "
LARGE_READ_OUT["'",1]=" X X "
LARGE_READ_OUT["'",2]=" XXX "
LARGE_READ_OUT["'",3]="     "
LARGE_READ_OUT["'",4]="     "

# Support functions
function GCD(){
	if [ $# -ne 2 ]; then error "GCD() got incorrect arg count"; fi
	if [ $1 -le 1 ]; then error "GCD() got too small argument"; fi
	if [ $2 -le 1 ]; then error "GCD() got too small argument"; fi
	NUM=$1
	DEN=$2
	REM=$((NUM%DEN))
	until [ "$REM" -eq 0 ]; do
		NUM=$DEN
		DEN=$REM
		REM=$((NUM%DEN))
	done
	echo $DEN
}

# Handle CLI args
SHOW_HELP=0
if [ "$#" -lt 1 ]; then SHOW_HELP=1; fi
SECT_LIST=''
SHOW_CALENDAR=0
SHOW_EMAIL=0
SHOW_MATRIX=0
SHOW_NEWS=0
SHOW_WEATHER=0
SHOW_STATS=0
while getopt -Q -q -o 'HCEMNSWd:' -n 'dash' -- $@; do
	case "$1" in
		-H) SHOW_HELP=1;     SECT_LIST+='H'; shift ;;
		-C) SHOW_CALENDAR=1; SECT_LIST+='C'; shift ;;
		-E) SHOW_EMAIL=1;    SECT_LIST+='E'; shift ;;
		-M) SHOW_MATRIX=1;   SECT_LIST+='M'; shift ;;
		-N) SHOW_NEWS=1;     SECT_LIST+='N'; shift ;;
		-S) SHOW_STATS=1;    SECT_LIST+='S'; shift ;;
		-W) SHOW_WEATHER=1;  SECT_LIST+='W'; shift ;;
		-d) DBG=1; shift ;;
		""|--) shift; break ;;
		*) error "Unrecognized option $1" ;;
	esac
done
if [[ -n "$1" ]]; then error "Unrecognized option $1"; fi
SECT_LIST=`echo $SECT_LIST | grep -o .`
SECTS=$(wc -l <<< "$SECT_LIST")

# Only in the case of the help menu being requested, print help and exit
if [ "$SHOW_HELP" = 1 ]; then
	echo -e "[1mSYNOPSIS[0m\n\
\t[1mdash[0m [[4moptions[0m]\n\n\
[1mOPTIONS[0m\n\
\t[1m-C[0m\n\
\t\tInclude a calendar readout in the output (you will be prompted for \
credentials).\n\n\
\t[1m-d[0m\n\
\t\tPrint debugging information (overrides value in your .dash.ini). No \
sections will be shown.\n\n\
\t[1m-E[0m\n\
\t\tInclude an email digest in the output (you will be prompted for \
credentials).\n\n\
\t[1m-H[0m\n\
\t\tOuput these instructions, and exit.\n\n\
\t[1m-M[0m\n\
\t\tInclude the matrix in the output\n\n\
\t[1m-N[0m\n\
\t\tInclude a news digest in the output.\n\n\
\t[1m-S[0m\n\
\t\tInclude system stats in the output (output may be reduced if run without \
privileges).\n\n\
\t[1m-W[0m\n\
\t\tInclude a weather forecast in the output.\n\n"
	exit
fi

# Additional configuration for individual sections
if [ "$SHOW_CALENDAR" = 1 ]; then
	CALENDAR_SECONDS_PER_POLL=$(load_config "CALENDAR_SECONDS_PER_POLL" "600")
fi
if [ "$SHOW_EMAIL" = 1 ]; then
	# Get INI values
	EMAIL_SECONDS_PER_POLL=$(load_config "EMAIL_SECONDS_PER_POLL" "300")
	EMAIL_SOURCE=$(load_config "EMAIL_SOURCE" "Gmail")
	# Prompt for credentials
	read -p "Please enter the username for your $EMAIL_SOURCE account: "\
		EMAIL_USER
	read -p "Password: " -s EMAIL_PASS
	echo ""
fi
if [ "$SHOW_MATRIX" = 1 ]; then
	MATRIX_SECONDS_PER_POLL=$(load_config "MATRIX_SECONDS_PER_POLL" "60")
fi
if [ "$SHOW_NEWS" = 1 ]; then
	NEWS_SECONDS_PER_POLL=$(load_config "NEWS_SECONDS_PER_POLL" "1800")
fi
if [ "$SHOW_STATS" = 1 ]; then
	# Get INI values
	STATS_SECONDS_PER_POLL=$(load_config "STATS_SECONDS_PER_POLL" "60")
	STATS_TEMPERATURE_UNITS=$(load_config "STATS_TEMPERATURE_UNITS" "F")
	if [ "$DISPLAY_ENCODING" == 'UTF8' ]; then
		STATS_DEGREE_SYMBOL="°"
	else
		STATS_DEGREE_SYMBOL="'"
	fi
fi
if [ "$SHOW_WEATHER" = 1 ]; then
	# Get INI values
	WEATHER_SECONDS_PER_POLL=$(load_config "WEATHER_SECONDS_PER_POLL" "600")
	WEATHER_NOAA_STATION_CODE=$(load_config "WEATHER_NOAA_STATION_CODE" "KNYC")
	WEATHER_TEMPERATURE_UNITS=$(load_config "WEATHER_TEMPERATURE_UNITS" "F")
	if [ "$WEATHER_TEMPERATURE_UNITS" == 'F' ]; then
		WEATHER_TEMPERATURE_OFFSET=0
	else
		WEATHER_TEMPERATURE_OFFSET=1
		WEATHER_TEMPERATURE_UNITS='C'
	fi
	if [ "$DISPLAY_ENCODING" == 'UTF8' ]; then
		WEATHER_DEGREE_SYMBOL="°"
	else
		WEATHER_DEGREE_SYMBOL="'"
	fi
fi

# Save the old screen, block input echo, and set signal traps
tput smcup
stty -echo
trap handleWindowChange WINCH
trap handleInterrupt INT
trap handleExit EXIT
TRAPS_SET=1

# Handle the actual rendering of dash sections
function render_sections(){
	# Get loop params from shell
	NEW_DATE=`date +%s`
	COLS=`tput cols`
	ROWS=`tput lines`
	RENDER_SECT_LIST=$SECT_LIST

	# Make sure there is enough space for anything
	if [ "$COLS" -lt "$SECTION_MIN_COLS" ] ||\
			[ "$ROWS" -lt "$SECTION_MIN_ROWS" ]; then
		clear
		msg "Screen too small!"
		read -t $REFRESH_RATE_SECONDS TMP
		continue
	fi

	# Compute optimal size per section
	BEST_X=1
	BEST_DIFF=100
	for TEMP_X in `seq 1 $SECTS`; do
		TEMP_Y=$(( SECTS/TEMP_X + (SECTS%TEMP_X ? 1 : 0) ))
		if [ "$COLS" -lt "$(( (SECTION_MIN_COLS+1)*TEMP_X-1 ))" ]\
				|| [ "$ROWS" -lt "$(( (SECTION_MIN_ROWS+1)*TEMP_Y-1 ))" ]; then
			continue
		fi
		RATING=$(( ( (ROWS * 165) / TEMP_Y) / (COLS / TEMP_X) - 100 ))
		DIFF="${RATING#-}"
		if [ "$DIFF" -lt "$BEST_DIFF" ]; then
			BEST_DIFF=$DIFF
			BEST_X=$TEMP_X
		fi
	done
	SECTS_X=BEST_X
	SECTS_Y=$(( SECTS/SECTS_X + (SECTS%SECTS_X ? 1 : 0) ))
	BLANK_SECTS=$(( SECTS_X*SECTS_Y - SECTS ))
	if [ "$BLANK_SECTS" -gt "0" ]; then
		SECTS=$(( SECTS + BLANK_SECTS ))
		if [ "$BLANK_SECTS" -eq "1" ]; then
			RENDER_SECT_LIST=$(echo $RENDER_SECT_LIST; echo "_")
		else
			RENDER_SECT_LIST=$(echo $RENDER_SECT_LIST; echo "_";
				printf "\n_%.0s" $(seq 2 $BLANK_SECTS))
		fi
	fi
	BASE_COLS=$(( COLS/SECTS_X ))
	BASE_ROWS=$(( ROWS/SECTS_Y ))
	EXTRA_X=$(( COLS-SECTS_X*BASE_COLS ))
	EXTRA_Y=$(( ROWS-SECTS_Y*BASE_ROWS ))
	SECTS_PROCESSED=0
	ROWS_PROCESSED=0
	COLS_PROCESSED=0

	# Make sure there is enough space for optimal layout
	if [ "$COLS" -lt "$(( (SECTION_MIN_COLS+1)*SECTS_X-1 ))" ]\
			|| [ "$ROWS" -lt "$(( (SECTION_MIN_ROWS+1)*SECTS_Y-1 ))" ]; then
		clear
		msg "Not enough space for all tiles"
		read -t $REFRESH_RATE_SECONDS TMP
		continue
	fi

	# Print debugging info about all section metrics
	if [ "$DBG" = 1 ]; then
		msg "Sections: $SECTS"
		msg "Layout: $SECTS_X x $SECTS_Y"
		msg "Size per section: $BASE_COLS x $BASE_ROWS"
		msg "Extra: $EXTRA_X, $EXTRA_Y"
	fi

	# Inner loop to handle each particular section
	PREV_SECT=""
	for CUR_SECT in $RENDER_SECT_LIST; do
		# Figure out the specific size of this section
		CUR_X=$((SECTS_PROCESSED%SECTS_X))
		CUR_Y=$((SECTS_PROCESSED/SECTS_X))
		BORDER_LEFT=$((CUR_X>0 ? 1 : 0))
		BORDER_TOP=$((CUR_Y>0 ? 1 : 0))
		CUR_COLS=$((BASE_COLS+(CUR_X+EXTRA_X>=SECTS_X ? 1 : 0)-BORDER_LEFT))
		CUR_ROWS=$((BASE_ROWS+(CUR_Y+EXTRA_Y>=SECTS_Y ? 1 : 0)-BORDER_TOP))
		NEW_SIZE=$CUR_COLS"x"$CUR_ROWS

		# Print debugging info about specific section
		if [ "$DBG" = 1 ]; then
			msg "Section '$CUR_SECT'  Size $NEW_SIZE"
		fi

		# Initialize freshness and printing vars
		DATA_FRESH=0
		SIZE_FRESH=0
		DATE=0
		DATA=''
		SIZE='0x0'
		DRAW=()
		NEW_DATA=''
		NEW_DRAW=()

		# Get seconds per poll for this section
		if [ "$CUR_SECT" == '_' ]; then
			SECONDS_PER_POLL=100000
		elif [ "$CUR_SECT" == 'C' ]; then
			SECONDS_PER_POLL=$CALENDAR_SECONDS_PER_POLL
		elif [ "$CUR_SECT" == 'E' ]; then
			SECONDS_PER_POLL=$EMAIL_SECONDS_PER_POLL
		elif [ "$CUR_SECT" == 'M' ]; then
			SECONDS_PER_POLL=$MATRIX_SECONDS_PER_POLL
		elif [ "$CUR_SECT" == 'N' ]; then
			SECONDS_PER_POLL=$NEWS_SECONDS_PER_POLL
		elif [ "$CUR_SECT" == 'S' ]; then
			SECONDS_PER_POLL=$STATS_SECONDS_PER_POLL
		elif [ "$CUR_SECT" == 'W' ]; then
			SECONDS_PER_POLL=$WEATHER_SECONDS_PER_POLL
		fi

		# Check any previous data
		if [ -f "$DASH_ROOT/$CUR_SECT"".dash" ]; then
			# See if data is still fresh
			OLD_DATE=$(head -n 1 "$DASH_ROOT/$CUR_SECT"".dash" | tail -n 1)
			OLD_DATA=$(head -n 2 "$DASH_ROOT/$CUR_SECT"".dash" | tail -n 1)
			if [ $OLD_DATE -ge $((NEW_DATE-SECONDS_PER_POLL)) ];
				then
				DATA_FRESH=1

				# See if the display size is still correct
				OLD_SIZE=$(head -n 3 "$DASH_ROOT/$CUR_SECT"".dash" | tail -n 1)
				OLD_DRAW=$(tail -n +4 "$DASH_ROOT/$CUR_SECT"".dash")
				if [ "$OLD_SIZE" == "$NEW_SIZE" ] && [ "$STARTED" == 1 ] ; then
					SIZE_FRESH=1
				fi
			fi
		fi

		# --- Blank -----------------------------------------
		if [ "$CUR_SECT" == '_' ]; then
			# Create an empty array of rows
			NEW_DRAW=($DISPLAY_ESCAPE_SPACE$(printf\
				" $DISPLAY_ESCAPE_SPACE%.0s" $(seq 2 $CUR_ROWS)))
			for i in `seq 0 $((CUR_ROWS-1))`; do NEW_DRAW[$i]=" "; done
		fi

		# --- Calendar --------------------------------------
		if [ "$CUR_SECT" == 'C' ]; then
			# If the data is old, fetch new data, otherwise use the old data
			if [ "$DATA_FRESH" = 0 ]; then
				NEW_DATA="---"
				DATA=$NEW_DATA
			else
				DATA=$OLD_DATA
			fi

			# If the drawing is old, redo it
			if [ "$SIZE_FRESH" = 0 ]; then
				# Expand the data into an array
				OLDIFS=$IFS
				IFS=";"
				DATA_ARRAY=($DATA)
				IFS=$OLDIFS

				# Create an empty array of rows
				NEW_DRAW=($DISPLAY_ESCAPE_SPACE$(printf\
					" $DISPLAY_ESCAPE_SPACE%.0s" $(seq 2 $CUR_ROWS)))
				for i in `seq 0 $((CUR_ROWS-1))`; do NEW_DRAW[$i]=" "; done

				# Smallest heights (3-10): just show most relevant info
				if [ "$CUR_ROWS" -lt 11 ]; then
					NEW_DRAW[0]=" "

				# Medium heights (11-25): add some formatting
				elif [ "$CUR_ROWS" -lt 26 ]; then
					# Row 0 has a heading
					NEW_DRAW[0]=" $COLOR_GRAY["$COLOR_ULINE"Calendar\
$COLOR_ULINE_OFF]$COLOR_NORM"

				# Largest heights (26+): the full Monty!
				else
					# Rows 0-1 have a heading
					if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
						NEW_DRAW[0]="$COLOR_GRAY Calendar $COLOR_NORM│"
						NEW_DRAW[1]="──────────────┘"
					else
						NEW_DRAW[0]="$COLOR_GRAY Calendar $COLOR_NORM|"
						NEW_DRAW[1]="--------------+"
					fi
				fi
			fi
		fi

		# --- Email -----------------------------------------
		if [ "$CUR_SECT" == 'E' ]; then
			# If the data is old, download new data, otherwise use the old data
			if [ "$DATA_FRESH" = 0 ]; then
				if [ "$EMAIL_SOURCE" == "Gmail" ]; then
					URL="https://mail.google.com/mail/feed/atom"
					FEED=$(curl -u "$EMAIL_USER:$EMAIL_PASS" --silent "$URL")
					MAILCOUNT=$(grep -oPm1 "(?<=<fullcount>)[^<]*"\
							<<< "$FEED")
					NEW_DATA=$MAILCOUNT
					OLDIFS=$IFS
					IFS=$'\n'
					FEED=($(grep -oPm1 "<entry>.*?</entry>" <<< "$FEED"))
					for i in `seq 0 $((MAILCOUNT - 1))`; do
						ENTRY=${FEED[$i]}
						D_senderName=$(grep -oPm1 "(?<=<name>)[^<]*"\
							<<< "$ENTRY" | head -n1)
						D_senderEmail=$(grep -oPm1 "(?<=<email>)[^<]*"\
							<<< "$ENTRY" | head -n1)
						D_subject=$(grep -oPm1 "(?<=<title>)[^<]*"\
							<<< "$ENTRY")
						D_date=$(date -d "$(grep -oPm1 "(?<=<modified>)[^<]*"\
							<<< "$ENTRY")" +%s)
						D_content=$(grep -oPm1 "(?<=<summary>)[^<]*"\
							<<< "$ENTRY")
						NEW_DATA=$NEW_DATA$(echo -e "\u07")
						NEW_DATA=$NEW_DATA$D_senderName$(echo -e "\u06")
						NEW_DATA=$NEW_DATA$D_senderEmail$(echo -e "\u06")
						NEW_DATA=$NEW_DATA$D_date$(echo -e "\u06")
						NEW_DATA=$NEW_DATA$D_subject$(echo -e "\u06")
						NEW_DATA=$NEW_DATA$D_content
					done
					IFS=$OLDIFS
					DATA=$NEW_DATA
				else
					DATA=$OLD_DATA
				fi
			else
				DATA=$OLD_DATA
			fi

			# If the drawing is old, redo it
			if [ "$SIZE_FRESH" = 0 ]; then
				# Create an empty array of rows
				NEW_DRAW=($DISPLAY_ESCAPE_SPACE$(printf\
					" $DISPLAY_ESCAPE_SPACE%.0s" $(seq 2 $CUR_ROWS)))
				for i in `seq 0 $((CUR_ROWS-1))`; do NEW_DRAW[$i]=" "; done

				# Expand the data into an array
				OLDIFS=$IFS
				IFS=$(echo -e "\u07")
				DATA_ARRAY=($DATA)
				IFS=$OLDIFS

				# Loop through each email message
				for i in `seq 0 ${DATA_ARRAY[0]}`; do
					# Get the email message pieces
					OLDIFS=$IFS
					IFS=$(echo -e "\u06")
					DATA_PIECES=(${DATA_ARRAY[$i]})
					IFS=$OLDIFS

					# Get the date
					if [ "$i" -gt 0 ]; then
						MESSAGE_AGE=$(( $(date '+%s') - ${DATA_PIECES[2]} ))
						if [ "$MESSAGE_AGE" -gt 31536000 ]; then
							DATE_STRING=$(date -d "@${DATA_PIECES[2]}" '+%F')
							DATE_COLOR=$COLOR_HEAT_0
						elif [ "$MESSAGE_AGE" -gt 5184000 ]; then
							DATE_STRING=$(date -d "@${DATA_PIECES[2]}"\
								'+%_m/%d')
							DATE_COLOR=$COLOR_HEAT_1
						elif [ "${DATA_PIECES[2]}" -lt\
								"$(date -d 'today 00:00:00' '+%s')" ]; then
							DATE_STRING=$(date -d "@${DATA_PIECES[2]}"\
								'+%b %e')
							DATE_COLOR=$COLOR_HEAT_2
						elif [ "$MESSAGE_AGE" -gt 300 ]; then
							DATE_STRING=$(date -d "@${DATA_PIECES[2]}"\
								'+%l:%M%P')
							DATE_COLOR=$COLOR_HEAT_3
						elif [ "$MESSAGE_AGE" -gt 120 ]; then
							DATE_STRING="$(( MESSAGE_AGE/60 )) minutes ago"
							DATE_COLOR=$COLOR_HEAT_4
						elif [ "$MESSAGE_AGE" -gt 60 ]; then
							DATE_STRING="1 minute ago"
							DATE_COLOR=$COLOR_HEAT_5
						else
							DATE_STRING="just now"
							DATE_COLOR=$COLOR_HEAT_6
						fi
					fi

					# Smallest heights (3-10): just show most relevant info
					if [ "$CUR_ROWS" -lt 11 ]; then
						# Break after too many rows of messages
						if [ "$(( i*1 + 2))" -ge "$CUR_ROWS" ]; then
							break
						# For the heading
						elif [ "$i" == 0 ]; then
							# Row 0 shows the message count
							NEW_DRAW[0]=$(center "No New Messages" $CUR_COLS)
							if [ "${DATA_ARRAY[$i]}" -gt 1 ]; then
								NEW_DRAW[0]=$(center $COLOR_GREN\
"${DATA_ARRAY[$i]}$COLOR_NORM New Messages" $CUR_COLS)
							elif [ "${DATA_ARRAY[$i]}" == 1 ]; then
								NEW_DRAW[0]=$(center $COLOR_GREN\
"1$COLOR_NORM New Message" $CUR_COLS)
							fi
						# For each message
						else
							# Row 1... Shows sender name and subject
							LEN_SENDER=${#DATA_PIECES[0]}
							if [ "$LEN_SENDER" -gt 15 ]; then
								LEN_SENDER=$(( ( (35*CUR_COLS)/100 ) > 15 ?\
									( (35*CUR_COLS)/100 ) : 15 ))
							fi
							LEN_DATE=${#DATE_STRING}
							NEW_DRAW[$i]="$COLOR_BOLD$(truncate\
								"${DATA_PIECES[0]}"\
								"$LEN_SENDER"\
							)$COLOR_BOLD_OFF - $(extend\
								"$(truncate\
									"${DATA_PIECES[3]}"\
									"$((CUR_COLS-(LEN_SENDER+4+LEN_DATE)))"\
								)"\
								"$((CUR_COLS-(LEN_SENDER+4+LEN_DATE)))"\
							) $DATE_COLOR$DATE_STRING$COLOR_NORM"
						fi

					# Medium heights (11-25): add some formatting
					elif [ "$CUR_ROWS" -lt 26 ]; then
						# Break after too many rows of messages
						if [ "$(( i*3 + 4))" -ge "$CUR_ROWS" ]; then
							break
						# For the heading
						elif [ "$i" == 0 ]; then
							# Row 0 has a heading
							NEW_DRAW[0]=" $COLOR_GRAY["$COLOR_ULINE"Email\
$COLOR_ULINE_OFF]$COLOR_NORM"

							# Row 1 shows the message count
							NEW_DRAW[1]=$(center "No New Messages" $CUR_COLS)
							if [ "${DATA_ARRAY[$i]}" -gt 1 ]; then
								NEW_DRAW[1]=$(center $COLOR_GREN\
"${DATA_ARRAY[$i]}$COLOR_NORM New Messages" $CUR_COLS)
							elif [ "${DATA_ARRAY[$i]}" == 1 ]; then
								NEW_DRAW[1]=$(center $COLOR_GREN\
"1$COLOR_NORM New Message" $CUR_COLS)
							fi
						# For each message
						else
							# Row 2... shows the sender's name and date
							NEW_DRAW[$(( i*3 ))]=$COLOR_GRAY"From:\
$COLOR_NORM $COLOR_BOLD$(extend\
								"$(truncate\
									"${DATA_PIECES[0]}"\
									"$(( $CUR_COLS - (${#DATE_STRING} + 7) ))"\
								)"\
								"$(( $CUR_COLS - (${#DATE_STRING} + 7) ))"\
							)$COLOR_BOLD_OFF \
							$DATE_COLOR$DATE_STRING$COLOR_NORM"

							# Row 3... shows the subject and message content
							LEN_SUBJECT=${#DATA_PIECES[3]}
							if [ "$LEN_SUBJECT" -gt "$((CUR_COLS - 6))" ]; then
								NEW_DRAW[$((i*3+1))]="$COLOR_ULINE$(truncate\
									"${DATA_PIECES[3]}"\
									$CUR_COLS\
								)$COLOR_ULINE_OFF"
							else
								NEW_DRAW[$((i*3+1))]="$COLOR_ULINE\
${DATA_PIECES[3]}$COLOR_ULINE_OFF - $(truncate\
									"${DATA_PIECES[4]}"\
									$(( CUR_COLS - (3+LEN_SUBJECT) ))
								)"
							fi
						fi

					# Largest heights (26+): the full Monty!
					else
						# Break after too many rows of messages
						if [ "$(( i*4 + 5))" -ge "$CUR_ROWS" ]; then
							break
						# For the heading
						elif [ "$i" == "0" ]; then
							# Rows 0-1 have a heading
							if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
								NEW_DRAW[0]="$COLOR_GRAY Email $COLOR_NORM│"
								NEW_DRAW[1]="───────┘"
							else
								NEW_DRAW[0]="$COLOR_GRAY Email $COLOR_NORM|"
								NEW_DRAW[1]="-------+"
							fi

							# Row 2 shows the message count
							NEW_DRAW[2]=$(center "No New Messages" $CUR_COLS)
							if [ "${DATA_ARRAY[$i]}" -gt 1 ]; then
								NEW_DRAW[2]=$(center $COLOR_GREN\
"${DATA_ARRAY[$i]}$COLOR_NORM New Messages" $CUR_COLS)
							elif [ "${DATA_ARRAY[$i]}" == 1 ]; then
								NEW_DRAW[2]=$(center $COLOR_GREN\
"1$COLOR_NORM New Message" $CUR_COLS)
							fi
						# For each message
						else
							# Row 3... shows the sender's info and date
							if [ "$(( ${#DATA_PIECES[0]} + ${#DATE_STRING}\
									+ 8))" -gt "$CUR_COLS" ]; then
								NEW_DRAW[$((i*4))]=$COLOR_GRAY"From:\
$COLOR_NORM $COLOR_BOLD$(truncate\
									"${DATA_PIECES[0]}"\
									"$(( $CUR_COLS - (${#DATE_STRING} + 7) ))"\
								)$COLOR_BOLD_OFF \
$DATE_COLOR$DATE_STRING$COLOR_NORM"
							elif [ "$(( ${#DATA_PIECES[0]}\
									+ ${#DATA_PIECES[1]} + ${#DATE_STRING}\
									+ 10))" -gt "$CUR_COLS" ]; then
								NEW_DRAW[$((i*4))]=$COLOR_GRAY"From:\
$COLOR_NORM $COLOR_BOLD${DATA_PIECES[0]}$COLOR_BOLD_OFF $(extend\
									"<$(truncate "${DATA_PIECES[1]}"\
										"$(( $CUR_COLS-(${#DATE_STRING}\
											+${#DATA_PIECES[0]}+10) ))"\
									)>"\
									"$(( $CUR_COLS-(${#DATE_STRING}\
										+${#DATA_PIECES[0]}+8) ))"\
								) $DATE_COLOR$DATE_STRING$COLOR_NORM"
							else
								NEW_DRAW[$((i*4))]=$COLOR_GRAY"From:\
$COLOR_NORM $COLOR_BOLD${DATA_PIECES[0]}$COLOR_BOLD_OFF $(extend\
									"<${DATA_PIECES[1]}>"\
									"$(( $CUR_COLS-(${#DATE_STRING}\
										+${#DATA_PIECES[0]}+8) ))"\
								) $DATE_COLOR$DATE_STRING$COLOR_NORM"
							fi

							# Row 4... shows the subject
							NEW_DRAW[$((i*4+1))]=$COLOR_GRAY"Subject:\
$COLOR_NORM $COLOR_ULINE$(truncate\
								"${DATA_PIECES[3]}"\
								$(( $CUR_COLS-9 ))\
							)$COLOR_ULINE_OFF"

							# Row 5... shows the message content
							NEW_DRAW[$((i*4+2))]="$(truncate\
								"${DATA_PIECES[4]}"\
								"$CUR_COLS"\
							)"
						fi
					fi
				done

				# Print the update date at the bottom
				SOURCE_STRING="mail"
				if [ "$EMAIL_SOURCE" == "Gmail" ]; then
					SOURCE_STRING="$COLOR_BLUE""G$COLOR_RED""m$COLOR_YELO"\
"a$COLOR_BLUE""i$COLOR_GREN""l$COLOR_RESET"
				fi
				NEW_DRAW[$(( CUR_ROWS-1 ))]=$(center\
					"Updated: $(date -d "@$NEW_DATE" "+%I:%M%p") | \
$SOURCE_STRING" $CUR_COLS)
				if [ "$CUR_ROWS" -gt 10 ]; then
					NEW_DRAW[$(( CUR_ROWS-2 ))]=$(center\
						"[ $COLOR_BLUE$EMAIL_USER$COLOR_RESET ]" $CUR_COLS)
				fi
			fi
		fi

		# --- Matrix ----------------------------------------
		if [ "$CUR_SECT" == 'M' ]; then
# TODO:
DATA_FRESH=0
			# If the data is old, fetch new data, otherwise use the old data
			if [ "$DATA_FRESH" = 0 ]; then
				MATRIX_QUOTES=(\
					"Wake up, $(whoami)..."\
					"The Matrix has you..."\
					"Follow the white rabbit..."\
					"Knock, knock, $(whoami)"\
					"Take the red pill"\
					"There is no spoon"\
					"The sound of inevitability"\
				);
				MATRIX_NUM_QUOTES=${#MATRIX_QUOTES[@]}
				if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
					MATRIX_CHARS=("ア" "イ" "ウ" "エ" "オ" "カ" "ガ" "キ" "ギ"
						"ク" "グ" "ケ" "ゲ" "コ" "ゴ" "サ" "ザ" "シ" "ジ" "ス"
						"ズ" "セ" "ゼ" "ソ" "ゾ" "タ" "ダ" "チ" "ヂ" "ツ" "ヅ"
						"テ" "デ" "ト" "ド" "ナ" "ニ" "ヌ" "ネ" "ノ" "ハ" "バ"
						"パ" "ヒ" "ビ" "ピ" "フ" "ブ" "プ" "ヘ" "ベ" "ペ" "ホ"
						"ボ" "ポ" "マ" "ミ" "ム" "メ" "モ" "ヤ" "ユ" "ヨ" "ラ"
						"リ" "ル" "レ" "ロ" "ワ" "ヰ" "ヱ" "ヲ" "ン" "ヴ" "・"
						"ー" "ヽ" "ヾ" "ヿ" "ㄅ" "ㄆ" "ㄇ" "ㄈ" "ㄉ" "ㄊ" "ㄋ"
						"ㄌ" "ㄍ" "ㄎ" "ㄏ" "ㄐ" "ㄑ" "ㄒ" "ㄓ" "ㄔ" "ㄕ" "ㄖ"
						"ㄗ" "ㄘ" "ㄙ" "ㄚ" "ㄛ" "ㄜ" "ㄝ" "ㄞ" "ㄟ" "ㄠ" "ㄡ"
						"ㄢ" "ㄣ" "ㄤ" "ㄥ" "ㄦ" "ㄧ" "ㄨ" "ㄩ"
					)
					MATRIX_CHAR_WIDTH=2
					MATRIX_NUM_CHARS=116
				else
					MATRIX_CHARS=("!" "\"" "#" "$" "%" "&" "'" "(" ")" "*" "+"
						"," "-" "." "/" "0" "1" "2" "3" "4" "5" "6" "7" "8" "9"
						":" ";" "<" "=" ">" "?" "@" "A" "B" "C" "D" "E" "F" "G"
						"H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S" "T" "U"
						"V" "W" "X" "Y" "Z" "[" "\\" "]" "^" "_" "\`" "a"   "b"
						"c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p"
						"q" "r" "s" "t" "u" "v" "w" "x" "y" "z" "{" "|" "}" "~"
					)
					MATRIX_CHAR_WIDTH=1
					MATRIX_NUM_CHARS=94
				fi
				NEW_DATA="$(( CUR_COLS/MATRIX_CHAR_WIDTH ))"
				for i in `seq 1 $NEW_DATA`; do
					if [ "$(( RANDOM%20 ))" -eq 0 ]; then
						TEXT_STRING=${MATRIX_QUOTES[$((
							RANDOM%MATRIX_NUM_QUOTES
						))]}
					else
						TEXT_STRING=""
						for j in `seq 0 $(( $RANDOM%16+5 ))`; do
							TEXT_STRING=$TEXT_STRING${MATRIX_CHARS[$((
								RANDOM%MATRIX_NUM_CHARS
							))]}
						done
					fi
msg "$TEXT_STRING"
					NEW_DATA=$NEW_DATA";"$TEXT_STRING
				done
				DATA=$NEW_DATA
			else
				DATA=$OLD_DATA
			fi

			# If the drawing is old, redo it
			if [ "$SIZE_FRESH" = 0 ]; then
				# Expand the data into an array
				OLDIFS=$IFS
				IFS=";"
				DATA_ARRAY=($DATA)
				IFS=$OLDIFS

				# Create an empty array of rows
				NEW_DRAW=($DISPLAY_ESCAPE_SPACE$(printf\
					" $DISPLAY_ESCAPE_SPACE%.0s" $(seq 2 $CUR_ROWS)))
				for i in `seq 0 $((CUR_ROWS-1))`; do NEW_DRAW[$i]=" "; done

				# Rows (n-2)-(n-1) show an update timestamp
				NEW_DRAW[$(( CUR_ROWS-2 ))]=$(center\
					"["$COLOR_GREN"The Matrix"$COLOR_RESET"]" $CUR_COLS)
				NEW_DRAW[$(( CUR_ROWS-1 ))]=$(center\
					"call trans opt: received. $(date "+%T")" $CUR_COLS)
			fi
		fi

		# --- News ------------------------------------------
		if [ "$CUR_SECT" == 'N' ]; then
			# If the data is old, fetch new data, otherwise use the old data
			if [ "$DATA_FRESH" = 0 ]; then
				NEW_DATA="---"
				DATA=$NEW_DATA
			else
				DATA=$OLD_DATA
			fi

			# If the drawing is old, redo it
			if [ "$SIZE_FRESH" = 0 ]; then
				# Expand the data into an array
				OLDIFS=$IFS
				IFS=";"
				DATA_ARRAY=($DATA)
				IFS=$OLDIFS

				# Create an empty array of rows
				NEW_DRAW=($DISPLAY_ESCAPE_SPACE$(printf\
					" $DISPLAY_ESCAPE_SPACE%.0s" $(seq 2 $CUR_ROWS)))
				for i in `seq 0 $((CUR_ROWS-1))`; do NEW_DRAW[$i]=" "; done

				# Smallest heights (3-10): just show most relevant info
				if [ "$CUR_ROWS" -lt 11 ]; then
					NEW_DRAW[0]=" "

				# Medium heights (11-25): add some formatting
				elif [ "$CUR_ROWS" -lt 26 ]; then
					# Row 0 has a heading
					NEW_DRAW[0]=" $COLOR_GRAY["$COLOR_ULINE"News\
$COLOR_ULINE_OFF]$COLOR_NORM"

				# Largest heights (26+): the full Monty!
				else
					# Rows 0-1 have a heading
					if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
						NEW_DRAW[0]="$COLOR_GRAY News $COLOR_NORM│"
						NEW_DRAW[1]="──────────────┘"
					else
						NEW_DRAW[0]="$COLOR_GRAY News $COLOR_NORM|"
						NEW_DRAW[1]="--------------+"
					fi
				fi
			fi
		fi

		# --- System Stats ----------------------------------
		if [ "$CUR_SECT" == 'S' ]; then
			# If the data is old, fetch new data, otherwise use the old data
			if [ "$DATA_FRESH" = 0 ]; then
				NEW_DATA=""

				# Get the hostname
				D_host=$(hostname)

				# Get OS info
				OS_INFO=$(lsb_release -a 2>&1)
				D_OS_id=$(grep -oPm1 "(?<=Distributor ID:).*"\
					<<< "$OS_INFO" | head -n1 | sed 's/\s*//g')
				D_OS_rel=$(grep -oPm1 "(?<=Release:).*"\
					<<< "$OS_INFO" | head -n1 | sed 's/\s*//g')
				D_OS_code=$(grep -oPm1 "(?<=Codename:).*"\
					<<< "$OS_INFO" | head -n1 | sed 's/\s*//g')
				if [ "$D_OS_id" == "Ubuntu" ]; then
					D_OS_verShort="$D_OS_id $D_OS_rel"
					D_OS_ver="$D_OS_id $(grep -oPm1 "(?<=VERSION=\")[^\"]*"\
						<<< "$(cat /etc/*-release)" | head -n1)"
				else
					D_OS_verShort="$D_OS_id $D_OS_rel"
					D_OS_ver="$D_OS_id$D_OS_rel, $D_OS_code"
				fi

				# Get system operation info
				TOP=$(top bsn1 | head -n2 | sed 's/[ \t]\+/\t/g')
				COM_FEED=$(echo "$TOP" | head -n1)
				D_COM_upDays=$(echo "$COM_FEED" | cut -f5)
				D_COM_upHours=$(echo "$COM_FEED" | cut -f7\
					| sed 's/^\([0-9]\+\):[0-9]\+,$/\1/')
				D_COM_upMins=$(echo "$COM_FEED" | cut -f7\
					| sed 's/^[0-9]\+:\([0-9]\+\),$/\1/')
				D_COM_users=$(echo "$COM_FEED" | cut -f8)

				# Get task info
				TSK_FEED=$(echo "$TOP" | tail -n1)
				D_TSK_tot=$(echo "$TSK_FEED" | cut -f2)
				D_TSK_run=$(echo "$TSK_FEED" | cut -f4)
				D_TSK_slp=$(echo "$TSK_FEED" | cut -f6)
				D_TSK_stp=$(echo "$TSK_FEED" | cut -f8)
				D_TSK_zmb=$(echo "$TSK_FEED" | cut -f10)

				# Get CPU usage info
				CPU_FEED=$(echo "$(mpstat -P ALL | grep -A16 '\ball\b'\
					| sed 's/[ \t]\+/\t/g')")
				D_CPU_count=$(echo "$CPU_FEED" | wc -l)
				D_CPU_all="$D_CPU_count"
				OLDIFS=$IFS
				IFS=$'\n'
				for oneCPU in $(echo "$CPU_FEED"); do
					D_CPU_id=$(echo "$oneCPU" | cut -f3)
					D_CPU_user=$(echo "$oneCPU" | cut -f4)
					D_CPU_kernel=$(echo "$oneCPU" | cut -f6)
					D_CPU_io=$(echo "$oneCPU" | cut -f7)
					D_CPU_interrupt=$(echo "$(echo "$oneCPU" | cut -f8)+\
$(echo "$oneCPU" | cut -f9)" | bc)
					D_CPU_idle=$(echo "$oneCPU" | cut -f13)
					D_CPU_all=$D_CPU_all$(echo -e "\u07")
					D_CPU_all=$D_CPU_all$D_CPU_id$(echo -e "\u06")
					D_CPU_all=$D_CPU_all$D_CPU_user$(echo -e "\u06")
					D_CPU_all=$D_CPU_all$D_CPU_kernel$(echo -e "\u06")
					D_CPU_all=$D_CPU_all$D_CPU_io$(echo -e "\u06")
					D_CPU_all=$D_CPU_all$D_CPU_interrupt$(echo -e "\u06")
					D_CPU_all=$D_CPU_all$D_CPU_idle
				done
				IFS=$OLDIFS

				# Get memory usage info
				MEM_FEED=$(free -tb | grep Total | sed 's/[ \t]\+/\t/g')
				D_MEM_size=$(echo "$MEM_FEED" | cut -f2)
				D_MEM_used=$(echo "$MEM_FEED" | cut -f3)
				D_MEM_free=$(echo "$MEM_FEED" | cut -f4)

				# Get filesystem usage info
				FSY_FEED=$(sudo df -lBK --output=source,target,size,pcent\
					| grep '^/dev' | sed 's/[ \t]\+/\t/g')
				D_FSY_count=$(echo "$FSY_FEED" | wc -l)
				D_FSY_all="$D_FSY_count"
				OLDIFS=$IFS
				IFS=$'\n'
				for oneFSY in $(echo "$FSY_FEED"); do
					D_FSY_mount=$(echo "$oneFSY" | cut -f2)
					D_FSY_size=$((\
						$(echo "$oneFSY" | tr -d 'K' | cut -f3)\
						* 1024\
					))
					D_FSY_used=$(echo "$oneFSY" | cut -f4 | tr -d "%"\
						| sed 's/^\(.*\)$/scale=4;\1\/100/' | bc)
					D_FSY_all=$D_FSY_all$(echo -e "\u07")
					D_FSY_all=$D_FSY_all$D_FSY_mount$(echo -e "\u06")
					D_FSY_all=$D_FSY_all$D_FSY_size$(echo -e "\u06")
					D_FSY_all=$D_FSY_all$D_FSY_used
				done
				IFS=$OLDIFS

				# Get temperature info
				TMP_FEED=$(sensors "-Au"\
					| grep '^[^:]\+$\|temp1_input:\|temp1_crit:'\
					| sed 's/^\s\+//' | sed 's/[ \t]\+/\t/g')
				D_TMP_count=$(( $(echo "$TMP_FEED" | wc -l) / 3 ))
				D_TMP_all="$D_TMP_count"
				D_TMP_sensor=""
				D_TMP_curTemp=""
				D_TMP_maxTemp=""
				OLDIFS=$IFS
				IFS=$'\n'
				for oneTMP in $(echo "$TMP_FEED"); do
					if [ ! -z "$(echo "$oneTMP" | grep 'temp1_input')" ]; then
						D_TMP_curTemp="$(echo "$oneTMP"\
							| sed 's/^.*[ \t]\+\([0-9]\+\.[0-9]\+\)$/\1/')"
					elif [ ! -z "$(echo "$oneTMP" | grep 'temp1_crit')" ]; then
						D_TMP_maxTemp="$(echo "$oneTMP"\
							| sed 's/^.*[ \t]\+\([0-9]\+\.[0-9]\+\)$/\1/')"
					else
						D_TMP_sensor=$oneTMP
					fi
					if [ ! -z "$D_TMP_sensor" ] && [ ! -z "$D_TMP_curTemp" ]\
							&& [ ! -z "$D_TMP_maxTemp" ]; then
						if [ "$STATS_TEMPERATURE_UNITS" == "F" ]; then
							D_TMP_curTemp=$(bc <<< "($D_TMP_curTemp*9+160)/5")
							D_TMP_maxTemp=$(bc <<< "($D_TMP_maxTemp*9+160)/5")
						fi
						D_TMP_all=$D_TMP_all$(echo -e "\u07")
						D_TMP_all=$D_TMP_all$D_TMP_sensor$(echo -e "\u06")
						D_TMP_all=$D_TMP_all$D_TMP_curTemp$(echo -e "\u06")
						D_TMP_all=$D_TMP_all$D_TMP_maxTemp
						D_TMP_sensor=""
						D_TMP_curTemp=""
						D_TMP_maxTemp=""
					fi
				done
				IFS=$OLDIFS

				# Get network info
				IP_URL='http://ipecho.net/plain'
				NWK_FEED=$(echo -e "Public\n"$(wget -qO- "$IP_URL");\
					ifconfig | grep '^[^ \t]\|inet addr:' |\
					sed 's/^.*inet addr:\([0-9\.]*\).*$/\1/' |\
					sed 's/^\([^ \t]\+\)[ \t].*$/\1/' |\
					sed 's/eth\([0-9]\+\)/Ethernet \1/' |\
					sed 's/^lo$/Loopback/'
				)
				D_NWK_count=$(( $(echo "$NWK_FEED" | wc -l) / 2 ))
				D_NWK_all="$D_NWK_count"
				POS=0
				OLDIFS=$IFS
				IFS=$'\n'
				for oneNWK in $NWK_FEED; do
					if [ "$POS" -eq 0 ]; then
						D_NWK_ipName=$oneNWK
						POS=1
					else
						D_NWK_ipAddress=$oneNWK
						D_NWK_all=$D_NWK_all$(echo -e "\u07")
						D_NWK_all=$D_NWK_all$D_NWK_ipName$(echo -e "\u06")
						D_NWK_all=$D_NWK_all$D_NWK_ipAddress
						POS=0
					fi
				done
				IFS=$OLDIFS

				# Fill out the data array
				NEW_DATA="$D_host;$D_OS_ver;$D_OS_verShort;$D_COM_upDays;\
$D_COM_upHours;$D_COM_upMins;$D_COM_users;$D_TSK_tot;$D_TSK_run;$D_TSK_slp;\
$D_TSK_stp;$D_TSK_zmb;$D_CPU_all;$D_MEM_size;$D_MEM_used;$D_MEM_free;\
$D_FSY_all;$D_TMP_all;$D_NWK_all"

				DATA=$NEW_DATA
			else
				DATA=$OLD_DATA
			fi

			# If the drawing is old, redo it
			if [ "$SIZE_FRESH" = 0 ]; then
				# Expand the data into an array
				OLDIFS=$IFS
				IFS=";"
				DATA_ARRAY=($DATA)
				IFS=$OLDIFS

				# Create an empty array of rows
				NEW_DRAW=($DISPLAY_ESCAPE_SPACE$(printf\
					" $DISPLAY_ESCAPE_SPACE%.0s" $(seq 2 $CUR_ROWS)))
				for i in `seq 0 $((CUR_ROWS-1))`; do NEW_DRAW[$i]=" "; done
				VBAR="$COLOR_DGRY$DISPLAY_SEPARATOR_V$COLOR_RESET"
				f=-1

				# Assign the heading based on standard heights
				if [ "$CUR_ROWS" -lt 11 ]; then
					:
				elif [ "$CUR_ROWS" -lt 26 ]; then
					NEW_DRAW[((++f))]=" $COLOR_GRAY["$COLOR_ULINE"System Stats\
$COLOR_ULINE_OFF]$COLOR_NORM"
				else
					if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
						NEW_DRAW[((++f))]=$COLOR_GRAY" System Stats "\
$COLOR_NORM"│"
						NEW_DRAW[((++f))]="──────────────┘"
					else
						NEW_DRAW[((++f))]=$COLOR_GRAY" System Stats "\
$COLOR_NORM"|"
						NEW_DRAW[((++f))]="--------------+"
					fi
				fi

				# Rows (f+1)-(g-1) show general information
				g=$f
				if [ "$g" -lt "$(( CUR_ROWS-5 ))" ]; then
					NEW_DRAW[((++g))]=$(center\
						"* "$COLOR_GRAY$COLOR_ULINE"General"$COLOR_RESET" *"\
						$CUR_COLS)
					NEW_DRAW[((++g))]=$COLOR_GRAY"OS Distro:$COLOR_RESET \
${DATA_ARRAY[1]}"
					if [ "$g" -lt "$(( CUR_ROWS-5 ))" ]; then
						NEW_DRAW[((++g))]=$COLOR_GRAY"Power time:$COLOR_RESET \
${DATA_ARRAY[3]} Days, ${DATA_ARRAY[4]} Hrs, ${DATA_ARRAY[5]} Mins"
						NEW_DRAW[((++g))]=$COLOR_GRAY"Users online:\
$COLOR_RESET ${DATA_ARRAY[6]}"
					fi
					((++g))
				fi

				# Rows (g+1)-(h-1) show task information
				h=$g
				if [ "$h" -lt "$(( CUR_ROWS-6 ))" ]; then
					NEW_DRAW[((++h))]=$(center "* "$COLOR_GRAY$COLOR_ULINE\
"Tasks"$COLOR_RESET" *" $CUR_COLS)
					NEW_DRAW[((++h))]=$COLOR_GRAY"Total:$COLOR_RESET $(extend\
						"${DATA_ARRAY[7]}" 5) ["
					BAR_WIDTH=$(( CUR_COLS-15 ))
					RUN_WIDTH=$(( DATA_ARRAY[8] / BAR_WIDTH +\
						(DATA_ARRAY[8]?1:0)))
					STP_WIDTH=$(( DATA_ARRAY[10] / BAR_WIDTH +\
						(DATA_ARRAY[10]?1:0)))
					ZMB_WIDTH=$(( DATA_ARRAY[11] / BAR_WIDTH +\
						(DATA_ARRAY[11]?1:0)))
					SLP_WIDTH=$(( BAR_WIDTH-(RUN_WIDTH+STP_WIDTH+ZMB_WIDTH) ))
					NEW_DRAW[$h]=${NEW_DRAW[$h]}$COLOR_GREN$(randomize "="\
						$RUN_WIDTH)
					NEW_DRAW[$h]=${NEW_DRAW[$h]}$COLOR_BLUE$(randomize "="\
						$SLP_WIDTH)
					NEW_DRAW[$h]=${NEW_DRAW[$h]}$COLOR_RED2$(randomize "="\
						$STP_WIDTH)
					NEW_DRAW[$h]=${NEW_DRAW[$h]}$COLOR_GRAY$(randomize "="\
						$ZMB_WIDTH)
					NEW_DRAW[$h]=${NEW_DRAW[$h]}"]"
					NEW_DRAW[((++h))]=""
					NEW_DRAW[$h]="${NEW_DRAW[$h]}$COLOR_BG_GREN \
$COLOR_BG_NORM$COLOR_GRAY""Run:$COLOR_NORM "$(( DATA_ARRAY[8] ))"  "
					NEW_DRAW[$h]="${NEW_DRAW[$h]}$COLOR_BG_BLUE \
$COLOR_BG_NORM$COLOR_GRAY""Slp:$COLOR_NORM "$(( DATA_ARRAY[9] ))"  "
					NEW_DRAW[$h]="${NEW_DRAW[$h]}$COLOR_BG_RED2 \
$COLOR_BG_NORM$COLOR_GRAY""Stp:$COLOR_NORM "$(( DATA_ARRAY[10] ))"  "
					NEW_DRAW[$h]="${NEW_DRAW[$h]}$COLOR_BG_GRAY \
$COLOR_BG_NORM$COLOR_GRAY""Zmb:$COLOR_NORM "$(( DATA_ARRAY[11] ))
					NEW_DRAW[$h]="$(center "${NEW_DRAW[$h]}" $CUR_COLS)"
					((++h))
				fi

				# Rows (h+1)-(i-1) show CPU info
				i=$h
				if [ "$i" -lt "$(( CUR_ROWS-9 ))" ]; then
					NEW_DRAW[((++i))]=$(center "* "$COLOR_GRAY$COLOR_ULINE\
"CPU"$COLOR_RESET" *" $CUR_COLS)
					CELL_WIDTH=$(( (CUR_COLS-SECTION_MIN_COLS)/15 + 6 ))
					NEW_DRAW[((++i))]="$COLOR_DGRY$DISPLAY_SEPARATOR_TL"\
$(randomize "$DISPLAY_SEPARATOR_H" 3)$DISPLAY_SEPARATOR_T\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_T\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_T\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_T\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_T\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_TR\
$COLOR_RESET
					NEW_DRAW[$i]=$(center "${NEW_DRAW[$i]}" $CUR_COLS)
					NEW_DRAW[((++i))]=$VBAR$COLOR_GRAY"CPU"$COLOR_RESET$VBAR\
$(centerex $COLOR_GRAY"User"$COLOR_RESET $CELL_WIDTH)$VBAR\
$(centerex $COLOR_GRAY"Kernel"$COLOR_RESET $CELL_WIDTH)$VBAR\
$(centerex $COLOR_GRAY"I/O"$COLOR_RESET $CELL_WIDTH)$VBAR\
$(centerex $COLOR_GRAY"Intrpt"$COLOR_RESET $CELL_WIDTH)$VBAR\
$(centerex $COLOR_GRAY"Idle"$COLOR_RESET $CELL_WIDTH)$VBAR
					NEW_DRAW[$i]=$(center "${NEW_DRAW[$i]}" $CUR_COLS)
					NEW_DRAW[((++i))]="$COLOR_DGRY$DISPLAY_SEPARATOR_L"\
$(randomize "$DISPLAY_SEPARATOR_H" 3)$DISPLAY_SEPARATOR_C\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_C\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_C\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_C\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_C\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_R$COLOR_RESET
					NEW_DRAW[$i]=$(center "${NEW_DRAW[$i]}" $CUR_COLS)
					CPU_DATA=${DATA_ARRAY[12]}
					OLDIFS=$IFS
					IFS=$(echo -e "\u07")
					CPU_DATA=($CPU_DATA)
					IFS=$OLDIFS
					for j in `seq 1 ${CPU_DATA[0]}`; do
						oneCPU=${CPU_DATA[$j]}
						OLDIFS=$IFS
						IFS=$(echo -e "\u06")
						PARTS=($oneCPU)
						IFS=$OLDIFS
						NEW_DRAW[((++i))]=$VBAR
						NEW_DRAW[$i]=${NEW_DRAW[$i]}$(centerex\
							"${PARTS[0]}" 3)$VBAR
						NEW_DRAW[$i]=${NEW_DRAW[$i]}$(centerex "$(heat\
							"${PARTS[1]}%" "0.00" "5")" $CELL_WIDTH)$VBAR
						NEW_DRAW[$i]=${NEW_DRAW[$i]}$(centerex "$(heat\
							"${PARTS[2]}%" "0.00" "5")" $CELL_WIDTH)$VBAR
						NEW_DRAW[$i]=${NEW_DRAW[$i]}$(centerex "$(heat\
							"${PARTS[3]}%" "0.00" "5")" $CELL_WIDTH)$VBAR
						NEW_DRAW[$i]=${NEW_DRAW[$i]}$(centerex "$(heat\
							"${PARTS[4]}%" "0.00" "5")" $CELL_WIDTH)$VBAR
						NEW_DRAW[$i]=${NEW_DRAW[$i]}$(centerex "$(heat\
							"${PARTS[5]}%" "100.00" "75")" $CELL_WIDTH)$VBAR
						NEW_DRAW[$i]=$(center "${NEW_DRAW[$i]}" $CUR_COLS)
						if [ "$i" -eq "$((CUR_ROWS-5))" ]; then break; fi
					done
					NEW_DRAW[((++i))]="$COLOR_DGRY$DISPLAY_SEPARATOR_BL"\
$(randomize "$DISPLAY_SEPARATOR_H" 3)$DISPLAY_SEPARATOR_B\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_B\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_B\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_B\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_B\
$(randomize "$DISPLAY_SEPARATOR_H" $CELL_WIDTH)$DISPLAY_SEPARATOR_BR\
$COLOR_RESET
					NEW_DRAW[$i]=$(center "${NEW_DRAW[$i]}" $CUR_COLS)
					((++i))
				fi

				# Rows (i+1)-(j-1) show memory usage
				j=$i
				if [ "$j" -lt "$(( CUR_ROWS-6 ))" ]; then
					NEW_DRAW[((++j))]=$(center "* "$COLOR_GRAY$COLOR_ULINE\
"Mem Use"$COLOR_RESET" *" $CUR_COLS)
					NEW_DRAW[((++j))]=$(center $COLOR_GRAY"Total:"$COLOR_RESET\
" $(fmt_mem "${DATA_ARRAY[13]}" 1)   "$COLOR_GRAY"Used:"$COLOR_RESET\
" $(fmt_mem "${DATA_ARRAY[14]}" 1)" $CUR_COLS)
					NEW_DRAW[((++j))]=$(percent_bar\
						$(echo "${DATA_ARRAY[14]}/${DATA_ARRAY[13]}" | bc -l)\
						$(( CUR_COLS/2 )) $COLOR_PURP $COLOR_BG_PURP)
					NEW_DRAW[$j]=$(center "${NEW_DRAW[$j]}" $CUR_COLS)
					((++j))
				fi

				# Rows (j+1)-(k-1) show filesystem usage
				k=$j
				if [ "$k" -lt "$(( CUR_ROWS-9 ))" ]; then
					NEW_DRAW[((++k))]=$(center "* "$COLOR_GRAY$COLOR_ULINE\
"Filesystems"$COLOR_RESET" *" $CUR_COLS)
					MOUNT_WIDTH=$(( (CUR_COLS-SECTION_MIN_COLS)/12 + 18 ))
					SIZE_WIDTH=$(( (CUR_COLS-SECTION_MIN_COLS)/18 + 8 ))
					BAR_WIDTH=$(( (CUR_COLS-SECTION_MIN_COLS)/9 + 10 ))
					NEW_DRAW[((++k))]="$COLOR_DGRY$DISPLAY_SEPARATOR_TL"\
$(randomize "$DISPLAY_SEPARATOR_H" $MOUNT_WIDTH)$DISPLAY_SEPARATOR_T\
$(randomize "$DISPLAY_SEPARATOR_H" $SIZE_WIDTH)$DISPLAY_SEPARATOR_T\
$(randomize "$DISPLAY_SEPARATOR_H" $BAR_WIDTH)$DISPLAY_SEPARATOR_TR$COLOR_RESET
					NEW_DRAW[$k]=$(center "${NEW_DRAW[$k]}" $CUR_COLS)
					NEW_DRAW[((++k))]=$VBAR\
$(extend $COLOR_GRAY" Mount"$COLOR_RESET $MOUNT_WIDTH)$VBAR\
$(centerex $COLOR_GRAY"Capacity"$COLOR_RESET $SIZE_WIDTH)$VBAR\
$(centerex $COLOR_GRAY"Usage"$COLOR_RESET $BAR_WIDTH)$VBAR
					NEW_DRAW[$k]=$(center "${NEW_DRAW[$k]}" $CUR_COLS)
					NEW_DRAW[((++k))]="$COLOR_DGRY$DISPLAY_SEPARATOR_L"\
$(randomize "$DISPLAY_SEPARATOR_H" $MOUNT_WIDTH)$DISPLAY_SEPARATOR_C\
$(randomize "$DISPLAY_SEPARATOR_H" $SIZE_WIDTH)$DISPLAY_SEPARATOR_C\
$(randomize "$DISPLAY_SEPARATOR_H" $BAR_WIDTH)$DISPLAY_SEPARATOR_R$COLOR_RESET
					NEW_DRAW[$k]=$(center "${NEW_DRAW[$k]}" $CUR_COLS)
					FSY_DATA=${DATA_ARRAY[16]}
					OLDIFS=$IFS
					IFS=$(echo -e "\u07")
					FSY_DATA=($FSY_DATA)
					IFS=$OLDIFS
					for FSYno in `seq 1 ${FSY_DATA[0]}`; do
						oneFSY=${FSY_DATA[$FSYno]}
						OLDIFS=$IFS
						IFS=$(echo -e "\u06")
						PARTS=($oneFSY)
						IFS=$OLDIFS
						NEW_DRAW[((++k))]=$VBAR
						NEW_DRAW[$k]=${NEW_DRAW[$k]}$(truncate "$(extend\
							" ${PARTS[0]}" $MOUNT_WIDTH)" $MOUNT_WIDTH)$VBAR
						NEW_DRAW[$k]=${NEW_DRAW[$k]}$(centerex "$(extendl\
							"$(fmt_mem ${PARTS[1]} 1)" 8)" $SIZE_WIDTH)$VBAR
						NEW_DRAW[$k]=${NEW_DRAW[$k]}$(centerex\
							"$(percent_bar\
								"${PARTS[2]}" $BAR_WIDTH\
								$COLOR_ORNG $COLOR_BG_ORNG\
							)"\
							$BAR_WIDTH\
						)$VBAR
						NEW_DRAW[$k]=$(center "${NEW_DRAW[$k]}" $CUR_COLS)
						if [ "$k" -eq "$((CUR_ROWS-5))" ]; then break; fi
					done
					NEW_DRAW[((++k))]="$COLOR_DGRY$DISPLAY_SEPARATOR_BL"\
$(randomize "$DISPLAY_SEPARATOR_H" $MOUNT_WIDTH)$DISPLAY_SEPARATOR_B\
$(randomize "$DISPLAY_SEPARATOR_H" $SIZE_WIDTH)$DISPLAY_SEPARATOR_B\
$(randomize "$DISPLAY_SEPARATOR_H" $BAR_WIDTH)$DISPLAY_SEPARATOR_BR$COLOR_RESET
					NEW_DRAW[$k]=$(center "${NEW_DRAW[$k]}" $CUR_COLS)
					((++k))
				fi

				# Rows (k+1)-(l-1) show temperature info
				l=$k
				if [ "$l" -lt "$(( CUR_ROWS-5 ))" ]; then
					NEW_DRAW[((++l))]=$(center "* "$COLOR_GRAY$COLOR_ULINE\
"Temperature"$COLOR_RESET" *" $CUR_COLS)
					SEG_WIDTH=$(( (CUR_COLS-SECTION_MIN_COLS)*3/56 + 3 ))
					BAR_WIDTH=$(( SEG_WIDTH*7 ))
					if [ "$STATS_TEMPERATURE_UNITS" == "F" ]; then
						MIN_TEMP="32"
					else
						MIN_TEMP="0"
					fi
					COLORS=("$COLOR_HEAT_0" "$COLOR_HEAT_1" "$COLOR_HEAT_2"\
						"$COLOR_HEAT_3" "$COLOR_HEAT_4" "$COLOR_HEAT_5"\
						"$COLOR_HEAT_6")
					BGCOLORS=("$COLOR_BG_HEAT_0" "$COLOR_BG_HEAT_1"\
						"$COLOR_BG_HEAT_2" "$COLOR_BG_HEAT_3"\
						"$COLOR_BG_HEAT_4" "$COLOR_BG_HEAT_5"\
						"$COLOR_BG_HEAT_6")
					TMP_DATA=${DATA_ARRAY[17]}
					OLDIFS=$IFS
					IFS=$(echo -e "\u07")
					TMP_DATA=($TMP_DATA)
					IFS=$OLDIFS
					for TMPno in `seq 1 ${TMP_DATA[0]}`; do
						oneTMP=${TMP_DATA[$TMPno]}
						OLDIFS=$IFS
						IFS=$(echo -e "\u06")
						PARTS=($oneTMP)
						IFS=$OLDIFS
						((++l))
						NEW_DRAW[$l]=$(truncate "${PARTS[0]}"\
							$(( CUR_COLS-(SEG_WIDTH*7+10) )))" "\
$(printf "%2d" "$MIN_TEMP")$STATS_DEGREE_SYMBOL$STATS_TEMPERATURE_UNITS
						for POS in `seq 0 $(( BAR_WIDTH-1 ))`; do
							if [ "$POS" -eq "$(( BAR_WIDTH *\
									(PARTS[1]-MIN_TEMP) / (PARTS[2]-MIN_TEMP)\
									))" ]; then
								NEW_DRAW[$l]=${NEW_DRAW[$l]}${BGCOLORS[$((\
									POS*7/BAR_WIDTH ))]}" "$COLOR_BG_NORM
							else
								NEW_DRAW[$l]=${NEW_DRAW[$l]}${COLORS[$((\
									POS*7/BAR_WIDTH ))]}"-"$COLOR_NORM
							fi
						done
						NEW_DRAW[$l]=${NEW_DRAW[$l]}\
$(printf "%3d" "${PARTS[2]}")$STATS_DEGREE_SYMBOL$STATS_TEMPERATURE_UNITS
						NEW_DRAW[$l]=$(center "${NEW_DRAW[$l]}" $CUR_COLS)
						if [ "$l" -eq "$(( CUR_ROWS-4))" ]; then break; fi
					done
					((++l))
				fi

				# Rows (l+1)-(m-1) show network info
				m=$l
				if [ "$m" -lt "$(( CUR_ROWS-5 ))" ]; then
					NEW_DRAW[((++m))]=$(center "* "$COLOR_GRAY$COLOR_ULINE\
"Network Addresses"$COLOR_RESET" *" $CUR_COLS)
					OLDIFS=$IFS
					IFS=$(echo -e "\u07")
					NWK_DATA=(${DATA_ARRAY[18]})
					IFS=$OLDIFS
					for NWKno in `seq 1 ${NWK_DATA[0]}`; do
						oneNWK=${NWK_DATA[$NWKno]}
						OLDIFS=$IFS
						IFS=$(echo -e "\u06")
						PARTS=($oneNWK)
						IFS=$OLDIFS
						((++m))
						NEW_DRAW[$m]=$COLOR_GRAY$(extendl "$(truncate\
							"${PARTS[0]}" 15)" 15)":$COLOR_RESET "$(extend\
							"${PARTS[1]}" 15)
						NEW_DRAW[$m]=$(center "${NEW_DRAW[$m]}" $CUR_COLS)
						if [ "$m" -eq "$(( CUR_ROWS-4))" ]; then break; fi
					done
					((++m))
				fi

				# Rows (n-2)-(n-1) show an update timestamp
				NEW_DRAW[$(( CUR_ROWS-2 ))]=$(center\
					"[$COLOR_RED${DATA_ARRAY[0]}$COLOR_RESET]" $CUR_COLS)
				NEW_DRAW[$(( CUR_ROWS-1 ))]=$(center\
					"Updated: $(date -d "@$NEW_DATE" "+%I:%M%p") | Dash"\
					$CUR_COLS)
			fi
		fi

		# --- Weather ---------------------------------------
		if [ "$CUR_SECT" == 'W' ]; then
			# If the data is old, download new data, otherwise use the old data
			if [ "$DATA_FRESH" = 0 ]; then
				URL="http://www.weather.gov/xml/current_obs/"
				DOWNLOAD=$(wget -q -O- "$URL$WEATHER_NOAA_STATION_CODE"".xml")
				D_cred=$(grep -oPm1 "(?<=<credit_URL>)[^<]*"\
					<<< "$DOWNLOAD")
				D_loc=$(grep -oPm1 "(?<=<location>)[^<]*"\
					<<< "$DOWNLOAD")
				D_lat=$(grep -oPm1 "(?<=<latitude>)[^<]*"\
					<<< "$DOWNLOAD")
				D_lon=$(grep -oPm1 "(?<=<longitude>)[^<]*"\
					<<< "$DOWNLOAD")
				D_time=$(grep -oPm1 "(?<=<observation_time_rfc822>)[^<]*"\
					<<< "$DOWNLOAD")
				D_weather=$(grep -oPm1 "(?<=<weather>)[^<]*"\
					<<< "$DOWNLOAD")
				D_temp_f=$(grep -oPm1 "(?<=<temp_f>)[^<]*"\
					<<< "$DOWNLOAD"); D_temp_f=$(sed "s/\..//" <<< "$D_temp_f")
				D_temp_c=$(grep -oPm1 "(?<=<temp_c>)[^<]*"\
					<<< "$DOWNLOAD"); D_temp_c=$(sed "s/\..//" <<< "$D_temp_c")
				D_hu=$(grep -oPm1 "(?<=<relative_humidity>)[^<]*"\
					<<< "$DOWNLOAD")
				D_w_dir=$(grep -oPm1 "(?<=<wind_dir>)[^<]*"\
					<<< "$DOWNLOAD")
				D_w_mph=$(grep -oPm1 "(?<=<wind_mph>)[^<]*"\
					<<< "$DOWNLOAD")
				D_chil_f=$(grep -oPm1 "(?<=<windchill_f>)[^<]*"\
					<<< "$DOWNLOAD")
				D_chil_c=$(grep -oPm1 "(?<=<windchill_c>)[^<]*"\
					<<< "$DOWNLOAD")
				D_vis=$(grep -oPm1 "(?<=<visibility_mi>)[^<]*"\
					<<< "$DOWNLOAD")
				if [ -z "$D_chil_f" ]; then D_chil_f='-'; fi
				if [ -z "$D_chil_c" ]; then D_chil_c='-'; fi
				if [ -z "$D_w_dir" ]; then D_w_dir='-'; fi
				if [ -z "$D_w_mph" ]; then D_w_mph='-'; fi
				NEW_DATA="$D_weather;$D_temp_f;$D_temp_c;$D_chil_f;$D_chil_c;\
$D_hu;$D_time;$D_cred;$D_w_dir;$D_w_mph;$D_vis;$D_loc;$D_lat;$D_lon\n"
				DATA=$NEW_DATA
			else
				DATA=$OLD_DATA
			fi

			# If the drawing is old, redo it
			if [ "$SIZE_FRESH" = 0 ]; then
				# Expand the data into an array
				OLDIFS=$IFS
				IFS=";"
				DATA_ARRAY=($DATA)
				IFS=$OLDIFS

				# Create an empty array of rows
				NEW_DRAW=($DISPLAY_ESCAPE_SPACE$(printf\
					" $DISPLAY_ESCAPE_SPACE%.0s" $(seq 2 $CUR_ROWS)))
				for i in `seq 0 $((CUR_ROWS-1))`; do NEW_DRAW[$i]=""; done

				# Smallest heights (3-10): just show most relevant info
				if [ "$CUR_ROWS" -lt 11 ]; then
					# Row 0 shows the weather status
					NEW_DRAW[0]=$(center "${DATA_ARRAY[0]}" $CUR_COLS)

					# Row 1 shows the temperature
					NEW_DRAW[1]=${DATA_ARRAY[$((1+WEATHER_TEMPERATURE_OFFSET\
						))]}$WEATHER_DEGREE_SYMBOL$WEATHER_TEMPERATURE_UNITS
					if [ "${DATA_ARRAY[$((3+WEATHER_TEMPERATURE_OFFSET))]}" \
						!= '-' ]; then
						NEW_DRAW[1]=${NEW_DRAW[1]}"  (feels like "\
${DATA_ARRAY[3]}$WEATHER_DEGREE_SYMBOL")"
					fi
					NEW_DRAW[1]=$(center "${NEW_DRAW[1]}" $CUR_COLS)

					# Row 2 shows the humidity
					NEW_DRAW[2]=$(center "Humidity: ${DATA_ARRAY[5]}%"\
						$CUR_COLS)

					# Row 3 shows the wind
					if [ "$CUR_ROWS" -gt 5 ]; then
						NEW_DRAW[3]=$(center "Wind: "${DATA_ARRAY[8]}\
" ${DATA_ARRAY[9]}mph" $CUR_COLS)
					fi

					# Row 4 shows visibility
					if [ "$CUR_ROWS" -gt 6 ]; then
						NEW_DRAW[4]=$(center "Visibility: ${DATA_ARRAY[10]}mi"\
							$CUR_COLS)
					fi

					# Row N-1 shows the update timestamp
					if [ "$CUR_ROWS" -gt 3 ]; then
						NEW_DRAW[$((CUR_ROWS-1))]=$(center "Updated: $(date -d\
							"${DATA_ARRAY[6]}" "+%I:%M%p") | ${DATA_ARRAY[7]}"\
							$CUR_COLS)
					fi

				# Medium heights (11-25): add some formatting
				elif [ "$CUR_ROWS" -lt 26 ]; then
					# Row 0 has a heading
					NEW_DRAW[0]=" $COLOR_GRAY["$COLOR_ULINE"Weather\
$COLOR_ULINE_OFF]$COLOR_NORM"

					# Rows 1-3 are the weather status and its border
					DECORATION_STRING=" "
					DECORATION_COLOR="$COLOR_NORM"
					# Fair
					if [ "${DATA_ARRAY[0]}" == "Fair" ]; then
						DECORATION_STRING="-$DISPLAY_ESCAPE_SPACE"
						DECORATION_COLOR="$COLOR_YELO"
					# A Few Clouds
					elif [ "${DATA_ARRAY[0]}" == "A Few Clouds" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="~☁$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING="~3$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_YELO"
					# Partly Cloudy
					elif [ "${DATA_ARRAY[0]}" == "Partly Cloudy" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁~$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING="3~$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_WHIT"
					# Mostly Cloudy
					elif [ "${DATA_ARRAY[0]}" == "Mostly Cloudy" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁~$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING="3~$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_GRAY"
					# Overcast with Haze
					elif [ "${DATA_ARRAY[0]}" == "Overcast with Haze" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁☁ᢆᢆ░3~"
						else
							DECORATION_STRING="333~~"
						fi
						DECORATION_COLOR="$COLOR_GRAY"
					# Overcast
					elif [ "${DATA_ARRAY[0]}" == "Overcast" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁☁☁3~"
						else
							DECORATION_STRING="333~~"
						fi
						DECORATION_COLOR="$COLOR_GRAY"
					# Light Rain
					elif [ "${DATA_ARRAY[0]}" == "Light Rain" ]; then
						DECORATION_STRING='``'"''\\\|   "
						DECORATION_COLOR="$COLOR_BLUE"
					# Rain
					elif [ "${DATA_ARRAY[0]}" == "Rain" ]; then
						DECORATION_STRING='````'"'''\\\\\|"
						DECORATION_COLOR="$COLOR_BLUE"
					# Light Freezing Rain Fog/Mist
					elif [ "${DATA_ARRAY[0]}" ==\
						"Light Freezing Rain Fog/Mist" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="\`\`\\ᢆ☁~   "
						else
							DECORATION_STRING="\`\`\\\\3~   "
						fi
						DECORATION_COLOR="$COLOR_LBLU"
					# Fog/Mist
					elif [ "${DATA_ARRAY[0]}" == "Fog/Mist" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁ᢆᢆ░~  "
						else
							DECORATION_STRING="3++#~  "
						fi
						DECORATION_COLOR="$COLOR_LGRY"
					# Light Snow
					elif [ "${DATA_ARRAY[0]}" == "Light Snow" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING=".❄\"$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING='.`"'"$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_WHIT"
					# Snow
					elif [ "${DATA_ARRAY[0]}" == "Snow" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="❄✲❄❅❆❈❉.\"$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING='"`.'"$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_WHIT"
					# ???
					else
						DECORATION_STRING="?$DISPLAY_ESCAPE_SPACE"
						DECORATION_COLOR="$COLOR_NORM"
					fi
					NEW_DRAW[1]=$DECORATION_COLOR$(center $(randomize\
						$DECORATION_STRING $(( ${#DATA_ARRAY[0]}+4 )))\
						$CUR_COLS)$COLOR_NORM
					NEW_DRAW[3]=$DECORATION_COLOR$(center $(randomize\
						$DECORATION_STRING $(( ${#DATA_ARRAY[0]}+4 )))\
						$CUR_COLS)$COLOR_NORM
					NEW_DRAW[1]=${NEW_DRAW[1]//$DISPLAY_ESCAPE_SPACE/ }
					NEW_DRAW[3]=${NEW_DRAW[3]//$DISPLAY_ESCAPE_SPACE/ }
					NEW_DRAW[2]=$DECORATION_COLOR$(center\
						"${DECORATION_STRING:0:1} ${DATA_ARRAY[0]} \
${DECORATION_STRING:0:1}" $CUR_COLS)$COLOR_NORM

					# Row 4 is blank

					# Row 5 shows the temperature
					NEW_DRAW[5]=${DATA_ARRAY[$((1+WEATHER_TEMPERATURE_OFFSET\
						))]}$WEATHER_DEGREE_SYMBOL$WEATHER_TEMPERATURE_UNITS
					if [ "${DATA_ARRAY[$((3+WEATHER_TEMPERATURE_OFFSET))]}" \
						!= '-' ]; then
						NEW_DRAW[5]=${NEW_DRAW[5]}"  (feels like "\
${DATA_ARRAY[3]}$WEATHER_DEGREE_SYMBOL")"
					fi
					NEW_DRAW[5]=$(center "${NEW_DRAW[5]}" $CUR_COLS)

					# Row 6 shows the humidity
					NEW_DRAW[6]=$(center "Humidity: ${DATA_ARRAY[5]}%"\
						$CUR_COLS)

					# Row 7 shows the wind
					if [ "$CUR_ROWS" -gt 9 ]; then
						if [ "${DATA_ARRAY[8]}" != '-' ]; then
							if [ "${DATA_ARRAY[9]}" != '-' ]; then
								NEW_DRAW[7]="Wind: ${DATA_ARRAY[8]} "\
${DATA_ARRAY[9]}"mph"
							else
								NEW_DRAW[7]="Wind: ${DATA_ARRAY[8]}"
							fi
						else
							if [ "${DATA_ARRAY[9]}" != '-' ]; then
								NEW_DRAW[7]="Wind: ${DATA_ARRAY[9]}mph"
							else
								NEW_DRAW[7]="Wind: - unavailable -"
							fi
						fi
						NEW_DRAW[7]=$(center "${NEW_DRAW[7]}" $CUR_COLS)
					fi

					# Row 8 shows visibility
					if [ "$CUR_ROWS" -gt 10 ]; then
						NEW_DRAW[8]=$(center "Visibility: ${DATA_ARRAY[10]}mi"\
							$CUR_COLS)
					fi

					# Row N-2 shows the name of the observatory
					if [ "$CUR_ROWS" -gt 11 ]; then
						NEW_DRAW[$((CUR_ROWS-2))]=$(center "$(truncate\
							"[$COLOR_YELO${DATA_ARRAY[11]}$COLOR_RESET]"\
							$CUR_COLS)" $CUR_COLS)
					fi

					# Row N-1 shows the update timestamp
					if [ "$CUR_ROWS" -gt 7 ]; then
						NEW_DRAW[$((CUR_ROWS-1))]=$(center "Updated: $(date -d\
							"${DATA_ARRAY[6]}" "+%I:%M%p") | ${DATA_ARRAY[7]}"\
							$CUR_COLS)
					fi

				# Largest heights (26+): the full Monty!
				else
					# Rows 0-1 have a heading
					if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
						NEW_DRAW[0]="$COLOR_GRAY Weather $COLOR_NORM│"
						NEW_DRAW[1]="─────────┘"
					else
						NEW_DRAW[0]="$COLOR_GRAY Weather $COLOR_NORM|"
						NEW_DRAW[1]="---------+"
					fi

					# Row 2 shows the weather status and
					# Rows 3-9 Show a large-size decorated temperature read-out
					DECORATION_STRING=" "
					DECORATION_COLOR="$COLOR_NORM"
					DECORATION_COLOR_BG="$COLOR_BG_NORM"
					# Fair
					if [ "${DATA_ARRAY[0]}" == "Fair" ]; then
						DECORATION_STRING="-$DISPLAY_ESCAPE_SPACE"
						DECORATION_COLOR="$COLOR_YELO"
						DECORATION_COLOR_BG="$COLOR_BG_YELO"
					# A Few Clouds
					elif [ "${DATA_ARRAY[0]}" == "A Few Clouds" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="~☁$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING="~3$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_YELO"
						DECORATION_COLOR_BG="$COLOR_BG_YELO"
					# Partly Cloudy
					elif [ "${DATA_ARRAY[0]}" == "Partly Cloudy" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁~$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING="3~$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_WHIT"
						DECORATION_COLOR_BG="$COLOR_BG_WHIT"
					# Mostly Cloudy
					elif [ "${DATA_ARRAY[0]}" == "Mostly Cloudy" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁~$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING="3~$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_GRAY"
						DECORATION_COLOR_BG="$COLOR_BG_GRAY"
					# Overcast with Haze
					elif [ "${DATA_ARRAY[0]}" == "Overcast with Haze" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁☁ᢆᢆ░3~"
						else
							DECORATION_STRING="333~~"
						fi
						DECORATION_COLOR="$COLOR_GRAY"
						DECORATION_COLOR_BG="$COLOR_BG_GRAY"
					# Overcast
					elif [ "${DATA_ARRAY[0]}" == "Overcast" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁☁☁3~"
						else
							DECORATION_STRING="333~~"
						fi
						DECORATION_COLOR="$COLOR_GRAY"
						DECORATION_COLOR_BG="$COLOR_BG_GRAY"
					# Light Rain
					elif [ "${DATA_ARRAY[0]}" == "Light Rain" ]; then
						DECORATION_STRING='``'"''\\\|   "
						DECORATION_COLOR="$COLOR_BLUE"
						DECORATION_COLOR_BG="$COLOR_BG_BLUE"
					# Rain
					elif [ "${DATA_ARRAY[0]}" == "Rain" ]; then
						DECORATION_STRING='````'"'''\\\\\|"
						DECORATION_COLOR="$COLOR_BLUE"
						DECORATION_COLOR_BG="$COLOR_BG_BLUE"
					# Light Freezing Rain Fog/Mist
					elif [ "${DATA_ARRAY[0]}" ==\
						"Light Freezing Rain Fog/Mist" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="\`\`\\ᢆ☁~   "
						else
							DECORATION_STRING="\`\`\\\\3~   "
						fi
						DECORATION_COLOR="$COLOR_LBLU"
						DECORATION_COLOR_BG="$COLOR_BG_LBLU"
					# Fog/Mist
					elif [ "${DATA_ARRAY[0]}" == "Fog/Mist" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="☁ᢆᢆ░~  "
						else
							DECORATION_STRING="3++#~  "
						fi
						DECORATION_COLOR="$COLOR_LGRY"
						DECORATION_COLOR_BG="$COLOR_BG_LGRY"
					# Light Snow
					elif [ "${DATA_ARRAY[0]}" == "Light Snow" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING=".❄\"$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING='.`"'"$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_WHIT"
						DECORATION_COLOR_BG="$COLOR_BG_WHIT"
					# Snow
					elif [ "${DATA_ARRAY[0]}" == "Snow" ]; then
						if [ "$DISPLAY_ENCODING" == "UTF8" ]; then
							DECORATION_STRING="❄✲❄❅❆❈❉.\"$DISPLAY_ESCAPE_SPACE"
						else
							DECORATION_STRING='"`.'"$DISPLAY_ESCAPE_SPACE"
						fi
						DECORATION_COLOR="$COLOR_WHIT"
						DECORATION_COLOR_BG="$COLOR_BG_WHIT"
					# ???
					else
						DECORATION_STRING="?$DISPLAY_ESCAPE_SPACE"
						DECORATION_COLOR="$COLOR_NORM"
						DECORATION_COLOR_BG="$COLOR_BG_NORM"
					fi
					LARGE_3=""
					LARGE_4=""
					LARGE_5=""
					LARGE_6=""
					LARGE_7=""
					LARGE_8=""
					LARGE_9=""
					TEMP=${DATA_ARRAY[$((1 + WEATHER_TEMPERATURE_OFFSET\
						))]}$WEATHER_DEGREE_SYMBOL$WEATHER_TEMPERATURE_UNITS
					for (( i=0; i<${#TEMP}; i++ )); do
						CHAR=${TEMP:$i:1}
						LARGE_3=$LARGE_3$(randomize $DECORATION_STRING 6)
						LARGE_4=$LARGE_4" "${LARGE_READ_OUT["$CHAR",0]}
						LARGE_5=$LARGE_5" "${LARGE_READ_OUT["$CHAR",1]}
						LARGE_6=$LARGE_6" "${LARGE_READ_OUT["$CHAR",2]}
						LARGE_7=$LARGE_7" "${LARGE_READ_OUT["$CHAR",3]}
						LARGE_8=$LARGE_8" "${LARGE_READ_OUT["$CHAR",4]}
						LARGE_9=$LARGE_9$(randomize $DECORATION_STRING 6)
					done
					LARGE_3=$(center $(randomize $DECORATION_STRING 2)\
$LARGE_3$(randomize $DECORATION_STRING 2) $CUR_COLS)
					LARGE_4=$(center "$(randomize $DECORATION_STRING \
1) $LARGE_4 $(randomize $DECORATION_STRING 1)" $CUR_COLS)
					LARGE_5=$(center "$(randomize $DECORATION_STRING \
1) $LARGE_5 $(randomize $DECORATION_STRING 1)" $CUR_COLS)
					LARGE_6=$(center "$(randomize $DECORATION_STRING \
1) $LARGE_6 $(randomize $DECORATION_STRING 1)" $CUR_COLS)
					LARGE_7=$(center "$(randomize $DECORATION_STRING \
1) $LARGE_7 $(randomize $DECORATION_STRING 1)" $CUR_COLS)
					LARGE_8=$(center "$(randomize $DECORATION_STRING \
1) $LARGE_8 $(randomize $DECORATION_STRING 1)" $CUR_COLS)
					LARGE_9=$(center $(randomize $DECORATION_STRING 2)\
$LARGE_9$(randomize $DECORATION_STRING 2) $CUR_COLS)
					LARGE_3=${LARGE_3//"$DISPLAY_ESCAPE_SPACE"/ }
					LARGE_4=${LARGE_4//"$DISPLAY_ESCAPE_SPACE"/ }
					LARGE_5=${LARGE_5//"$DISPLAY_ESCAPE_SPACE"/ }
					LARGE_6=${LARGE_6//"$DISPLAY_ESCAPE_SPACE"/ }
					LARGE_7=${LARGE_7//"$DISPLAY_ESCAPE_SPACE"/ }
					LARGE_8=${LARGE_8//"$DISPLAY_ESCAPE_SPACE"/ }
					LARGE_9=${LARGE_9//"$DISPLAY_ESCAPE_SPACE"/ }
					LARGE_4=${LARGE_4//"X"/$DECORATION_COLOR_BG $COLOR_BG_NORM}
					LARGE_5=${LARGE_5//"X"/$DECORATION_COLOR_BG $COLOR_BG_NORM}
					LARGE_6=${LARGE_6//"X"/$DECORATION_COLOR_BG $COLOR_BG_NORM}
					LARGE_7=${LARGE_7//"X"/$DECORATION_COLOR_BG $COLOR_BG_NORM}
					LARGE_8=${LARGE_8//"X"/$DECORATION_COLOR_BG $COLOR_BG_NORM}
					NEW_DRAW[2]=$DECORATION_COLOR$(center "${DATA_ARRAY[0]}"\
						$CUR_COLS)$COLOR_NORM
					NEW_DRAW[3]=$DECORATION_COLOR$LARGE_3$COLOR_NORM
					NEW_DRAW[4]=$DECORATION_COLOR$LARGE_4$COLOR_NORM
					NEW_DRAW[5]=$DECORATION_COLOR$LARGE_5$COLOR_NORM
					NEW_DRAW[6]=$DECORATION_COLOR$LARGE_6$COLOR_NORM
					NEW_DRAW[7]=$DECORATION_COLOR$LARGE_7$COLOR_NORM
					NEW_DRAW[8]=$DECORATION_COLOR$LARGE_8$COLOR_NORM
					NEW_DRAW[9]=$DECORATION_COLOR$LARGE_9$COLOR_NORM

					# Row 10 shows the effective temperature
					if [ "${DATA_ARRAY[$((3+WEATHER_TEMPERATURE_OFFSET))]}" \
						!= '-' ]; then
						NEW_DRAW[10]=$(center\
						"(feels like ${DATA_ARRAY[3]}$WEATHER_DEGREE_SYMBOL)"\
						$CUR_COLS)
					else
						NEW_DRAW[10]=""
					fi

					# Row 11 is blank

					# Row 12 shows the humidity
					NEW_DRAW[12]=$(center "Humidity: ${DATA_ARRAY[5]}%"\
						$CUR_COLS)

					# Row 13 shows the wind
					if [ "${DATA_ARRAY[8]}" != '-' ]; then
						if [ "${DATA_ARRAY[9]}" != '-' ]; then
							NEW_DRAW[13]="Wind: ${DATA_ARRAY[8]} "\
${DATA_ARRAY[9]}"mph"
						else
							NEW_DRAW[13]="Wind: ${DATA_ARRAY[8]}"
						fi
					else
						if [ "${DATA_ARRAY[9]}" != '-' ]; then
							NEW_DRAW[13]="Wind: ${DATA_ARRAY[9]}mph"
						else
							NEW_DRAW[13]="Wind: - unavailable -"
						fi
					fi
					NEW_DRAW[13]=$(center "${NEW_DRAW[13]}" $CUR_COLS)

					# Row 14 shows visibility
					NEW_DRAW[14]=$(center "Visibility: ${DATA_ARRAY[10]}mi"\
						$CUR_COLS)

					# Rows 15 and 16 are blank

					# Rows 17-(N-3) have a weather graphic
					if [ "$CUR_ROWS" -gt "20" ]; then
						for i in `seq 17 $((CUR_ROWS-4))`; do
							LINE_ESCAPED=$(center "$(randomize "\
$DECORATION_STRING$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE\
$DISPLAY_ESCAPE_SPACE$DISPLAY_ESCAPE_SPACE" $((CUR_COLS/2)))" $CUR_COLS)
							NEW_DRAW[$i]=$DECORATION_COLOR\
${LINE_ESCAPED//"$DISPLAY_ESCAPE_SPACE"/ }$COLOR_NORM
						done
					fi

					# Row N-2 shows the name of the observatory
					NEW_DRAW[$((CUR_ROWS-2))]=$(center "$(truncate\
						"[$COLOR_YELO${DATA_ARRAY[11]}$COLOR_RESET]"\
						$CUR_COLS)" $CUR_COLS)

					# Row N-1 shows the update timestamp
					NEW_DRAW[$((CUR_ROWS-1))]=$(center "Updated: $(date -d\
						"${DATA_ARRAY[6]}" "+%I:%M%p") | ${DATA_ARRAY[7]}"\
						$CUR_COLS)
				fi
			fi
		fi

		# Get the correct data and date
		if [ "$DATA_FRESH" = 0 ]; then
			if [ "$DBG" = 1 ]; then msg "New Data"; fi
			DATA=$NEW_DATA
			DATE=$NEW_DATE
		else
			if [ "$DBG" = 1 ]; then msg "Old Data"; fi
			DATA=$OLD_DATA
			DATE=$OLD_DATE
		fi

		# Get the correct size and drawing
		if [ "$SIZE_FRESH" = 0 ]; then
			if [ "$DBG" = 1 ]; then msg "New Drawing"; fi
			SIZE=$NEW_SIZE
			DRAW=("${NEW_DRAW[@]}")
		else
			if [ "$DBG" = 1 ]; then msg "Old Drawing"; fi
			SIZE=$OLD_SIZE
			DRAW=("${OLD_DRAW[@]}")
		fi

		# If anything has changed, write to the dash file and print it
		if [ "$((DATA_FRESH+SIZE_FRESH+STARTED))" -lt 3 ]; then
			# Print data to file
			echo "$DATE" > "$DASH_ROOT/$CUR_SECT"".dash"
			echo "$DATA" >> "$DASH_ROOT/$CUR_SECT"".dash"
			echo "$SIZE" >> "$DASH_ROOT/$CUR_SECT"".dash"
			printf '%s\n' "${DRAW[@]}"  >> "$DASH_ROOT/$CUR_SECT"".dash"

			if [ "$DBG" = 0 ]; then
				# Print top border as needed
				if [ "$BORDER_TOP" = 1 ]; then
					tput cup $ROWS_PROCESSED $COLS_PROCESSED
					if [ "$CUR_X" -gt 0 ]; then
						if [[ "$PREV_SECT" != "_" ]]; then
							echo -n $DISPLAY_SEPARATOR_C;
						else
							echo -n $DISPLAY_SEPARATOR_CB;
						fi
					fi
					if [ "$DISPLAY_SEPARATOR_H" == "-" ]; then
						echo "$(head -c "$CUR_COLS" < "/dev/zero"|tr '\0' '-')"
					else
						printf "$DISPLAY_SEPARATOR_H%.0s" $(seq 1 $CUR_COLS)
					fi
				fi

				# Print left border and content
				for i in `seq 0 $((CUR_ROWS-1))`; do
					# Clear the row first
					tput cup $((ROWS_PROCESSED+BORDER_TOP+i))\
						$((COLS_PROCESSED+BORDER_LEFT))
					printf "%*s" $CUR_COLS " "
					# Reset the cursor and print content
					tput cup $((ROWS_PROCESSED+BORDER_TOP+i)) $COLS_PROCESSED
					if [ "$BORDER_LEFT" = 1 ]; then
						if [[ "$PREV_SECT" != "_" ]]; then
							echo -n "$DISPLAY_SEPARATOR_V";
						fi
					fi
					echo -n "${DRAW[$i]}"
				done
			fi
		fi

		# Done with one section drawing
		if [ "$CUR_X" -eq "$((SECTS_X-1))" ]; then
			COLS_PROCESSED=0
			ROWS_PROCESSED=$((ROWS_PROCESSED+CUR_ROWS+BORDER_TOP))
		else
			COLS_PROCESSED=$((COLS_PROCESSED+CUR_COLS+BORDER_LEFT))
		fi
		((++SECTS_PROCESSED))
		PREV_SECT=$CUR_SECT
	done

	# Wait until the next refresh
	STARTED=1
	TMP="nop"
	read -t $REFRESH_RATE_SECONDS TMP
	if [ "$TMP" == "r" ]; then STARTED=0; fi
}

# Loop the section processing code ad infinitum (exit with CTRL+c)
while true; do
	render_sections
done
